PINYIN_DICT = {
    # 'a' 行
    'a': ['ɑ'],
    'ha': ['hɑ'],
    'pa': ['pɑ'],
    'pha': ['pʰɑ'],
    'ba': ['bɑ'],
    'ma': ['mɑ'],
    'ta': ['tɑ'],
    'tha': ['tʰɑ'],
    'na': ['nɑ'],
    'la': ['lɑ'],
    'tsa': ['tsɑ'],
    'tsha': ['tsʰɑ'],
    'sa': ['sɑ'],
    'ka': ['kɑ'],
    'kha': ['kʰɑ'],
    'ga': ['gɑ'],
    'nga': ['ŋɑ'],

    'ann': ['ɑ̃'],
    'hann': ['hɑ̃'],
    'phann': ['pʰɑ̃'],
    'tann': ['tɑ̃'],
    'thann': ['tʰɑ̃'],
    'tsann': ['tsɑ̃'],
    'tshann': ['tsʰɑ̃'],
    'sann': ['sɑ̃'],
    'kann': ['kɑ̃'],
    'khann': ['kʰɑ̃'],

    'ah': ['ɑʔ'],
    'hah': ['hɑʔ'],
    'pah': ['pɑʔ'],
    'phah': ['pʰɑʔ'],
    'bah': ['bɑʔ'],
    'mah': ['mɑʔ'],
    'tah': ['tɑʔ'],
    'thah': ['tʰɑʔ'],
    'nah': ['nɑʔ'],
    'lah': ['lɑʔ'],
    'tsah': ['tsɑʔ'],
    'tshah': ['tsʰɑʔ'],
    'sah': ['sɑʔ'],
    'kah': ['kɑʔ'],
    'khah': ['kʰɑʔ'],

    'annh': ['ɑ̃ʔ'],
    'hannh': ['hɑ̃ʔ'],
    'sannh': ['sɑ̃ʔ'],

    'am': ['ɑm'],
    'ham': ['ham'],
    'tam': ['tɑm'],
    'tham': ['tʰɑm'],
    'lam': ['lɑm'],
    'tsam': ['tsɑm'],
    'tsham': ['tsʰɑm'],
    'sam': ['sɑm'],
    'kam': ['kɑm'],
    'kham': ['kʰɑm'],
    'gam': ['gɑm'],

    'an': ['an'],
    'han': ['hɑn'],
    'pan': ['pɑn'],
    'phan': ['pʰɑn'],
    'ban': ['bɑn'],
    'tan': ['tɑn'],
    'than': ['tʰɑn'],
    'lan': ['lɑn'],
    'tsan': ['tsɑn'],
    'tshan': ['tsʰɑn'],
    'san': ['sɑn'],
    'kan': ['kɑn'],
    'khan': ['kʰɑn'],
    'gan': ['gɑn'],

    'ang': ['ɑŋ'],
    'hang': ['hɑŋ'],
    'pang': ['pɑŋ'],
    'phang': ['pʰɑŋ'],
    'bang': ['bɑŋ'],
    'tang': ['tɑŋ'],
    'thang': ['tʰɑŋ'],
    'lang': ['lɑŋ'],
    'tsang': ['tsɑŋ'],
    'tshang': ['tsʰɑŋ'],
    'sang': ['sɑŋ'],
    'kang': ['kɑŋ'],
    'khang': ['kʰɑŋ'],
    'gang': ['gɑŋ'],

    'ap': ['ap̚'],
    'hap': ['hap̚'],
    'tap': ['tɑp̚'],
    'thap': ['tʰɑp̚'],
    'lap': ['lɑp̚'],
    'tsap': ['tsɑp̚'],
    'tshap': ['tsʰɑp̚'],
    'sap': ['sɑp̚'],
    'kap': ['kɑp̚'],
    'khap': ['kʰɑp̚'],

    'at': ['at̚'],
    'hat': ['hɑt̚'],
    'pat': ['pɑt̚'],
    'phat': ['pʰɑt̚'],
    'bat': ['bɑt̚'],
    'tat': ['tɑt̚'],
    'that': ['tʰɑt̚'],
    'lat': ['lɑt̚'],
    'tsat': ['tsɑt̚'],
    'tshat': ['tsʰɑt̚'],
    'sat': ['sɑt̚'],
    'kat': ['kɑt̚'],
    'khat': ['kʰɑt̚'],

    'ak': ['ɑk̚'],
    'hak': ['hɑk̚'],
    'pak': ['pɑk̚'],
    'phak': ['pʰɑk̚'],
    'bak': ['bɑk̚'],
    'tak': ['tɑk̚'],
    'thak': ['tʰɑk̚'],
    'lak': ['lɑk̚'],
    'tsak': ['tsɑk̚'],
    'tshak': ['tsʰɑk̚'],
    'sak': ['sɑk̚'],
    'kak': ['kɑk̚'],
    'khak': ['kʰɑk̚'],
    'gak': ['gɑk̚'],

    # 'ai' 行
    'ai': ['ɑɪ'],
    'hai': ['hɑɪ'],
    'pai': ['pɑɪ'],
    'phai': ['pʰɑɪ'],
    'bai': ['bɑɪ'],
    'mai': ['mɑɪ'],
    'tai': ['tɑɪ'],
    'thai': ['tʰɑɪ'],
    'nai': ['nɑɪ'],
    'lai': ['lɑɪ'],
    'tsai': ['tsɑɪ'],
    'tshai': ['tsʰɑɪ'],
    'sai': ['sɑɪ'],
    'kai': ['kɑɪ'],
    'khai': ['kʰɑɪ'],
    'gai': ['gɑɪ'],
    'ngai': ['ŋɑɪ'],

    'ainn': ['ɑ̃ɪ'],
    'hainn': ['hɑ̃ɪ'],
    'phainn': ['pʰɑ̃ɪ'],
    'tainn': ['tɑ̃ɪ'],
    'tsainn': ['tsɑ̃ɪ'],
    'kainn': ['kɑ̃ɪ'],
    'khainn': ['kʰɑ̃ɪ'],

    'aih': ['ɑɪʔ'],
    'haih': ['hɑɪʔ'],
    'laih': ['lɑɪʔ'],
    'saih': ['sɑɪʔ'],

    # 'au' 行
    'au': ['ɑu'],
    'hau': ['hɑu'],
    'pau': ['pɑu'],
    'phau': ['pʰɑu'],
    'bau': ['bɑu'],
    'mau': ['mɑu'],
    'tau': ['tɑu'],
    'thau': ['tʰɑu'],
    'nau': ['nɑu'],
    'lau': ['lɑu'],
    'tsau': ['tsɑu'],
    'tshau': ['tsʰɑu'],
    'sau': ['sɑu'],
    'kau': ['kɑu'],
    'khau': ['kʰɑu'],
    'gau': ['gɑu'],
    'ngau': ['ŋɑu'],

    'auann': ['ɑ̃u'],

    'auh': ['ɑuʔ'],
    'phauh': ['pʰɑuʔ'],
    'mauh': ['mɑuʔ'],
    'tauh': ['tɑuʔ'],
    'nauh': ['nɑuʔ'],
    'lauh': ['lɑuʔ'],
    'tshauh': ['tsʰɑuʔ'],
    'kauh': ['kɑuʔ'],
    'ngauh': ['ŋɑuʔ'],

    # 'e' 行
    'e': ['e'],
    'he': ['he'],
    'pe': ['pe'],
    'phe': ['pʰe'],
    'be': ['be'],
    'me': ['me'],
    'te': ['te'],
    'the': ['tʰe'],
    'ne': ['ne'],
    'le': ['le'],
    'tse': ['tse'],
    'tshe': ['tsʰe'],
    'se': ['se'],
    'ke': ['ke'],
    'khe': ['kʰe'],
    'ge': ['ge'],
    'nge': ['ŋe'],

    'enn': ['ẽ'],
    'henn': ['hẽ'],
    'penn': ['pẽ'],
    'phenn': ['pʰẽ'],
    'tenn': ['tẽ'],
    'thenn': ['tʰẽ'],
    'tsenn': ['tsẽ'],
    'tshenn': ['tsʰẽ'],
    'senn': ['sẽ'],
    'kenn': ['kẽ'],
    'khenn': ['kʰẽ'],

    'eh': ['eʔ'],
    'heh': ['heʔ'],
    'peh': ['peʔ'],
    'pheh': ['pʰeʔ'],
    'beh': ['beʔ'],
    'meh': ['meʔ'],
    'teh': ['teʔ'],
    'theh': ['tʰeʔ'],
    'neh': ['neʔ'],
    'leh': ['leʔ'],
    'tseh': ['tseʔ'],
    'tsheh': ['tsʰeʔ'],
    'seh': ['seʔ'],
    'keh': ['keʔ'],
    'kheh': ['kʰeʔ'],
    'geh': ['geʔ'],
    'ngeh': ['ŋeʔ'],

    'ennh': ['ẽʔ'],
    'hennh': ['hẽʔ'],
    'khennh': ['kʰẽʔ'],

    # 'i' 行
    'i': ['i'],
    'hi': ['hi'],
    'pi': ['pi'],
    'phi': ['pʰi'],
    'bi': ['bi'],
    'mi': ['mi'],
    'ti': ['ti'],
    'thi': ['tʰi'],
    'ni': ['ni'],
    'li': ['li'],
    'tsi': ['tsi'],
    'tshi': ['tsʰi'],
    'ji': ['ʥi'],
    'si': ['si'],
    'ki': ['ki'],
    'khi': ['kʰi'],
    'gi': ['gi'],
    'ngi': ['ŋi'],

    'inn': ['ĩ'],
    'hinn': ['hĩ'],
    'pinn': ['pĩ'],
    'phinn': ['pʰĩ'],
    'tinn': ['tĩ'],
    'thinn': ['tʰĩ'],
    'tsinn': ['tsĩ'],
    'tshinn': ['tsʰĩ'],
    'sinn': ['sĩ'],
    'kinn': ['kĩ'],
    'khinn': ['kʰĩ'],

    'ih': ['iʔ'],
    'pih': ['piʔ'],
    'phih': ['pʰiʔ'],
    'bih': ['biʔ'],
    'mih': ['miʔ'],
    'tih': ['tiʔ'],
    'thih': ['tʰiʔ'],
    'nih': ['niʔ'],
    'lih': ['liʔ'],
    'tsih': ['tsiʔ'],
    'tshih': ['tsʰiʔ'],
    'sih': ['siʔ'],
    'kih': ['kiʔ'],
    'khih': ['kʰiʔ'],

    'im': ['im'],
    'him': ['him'],
    'tim': ['tim'],
    'thim': ['tʰim'],
    'lim': ['lim'],
    'tsim': ['tsim'],
    'tshim': ['tsʰim'],
    'jim': ['ʥim'],
    'sim': ['sim'],
    'kim': ['kim'],
    'khim': ['kʰim'],
    'gim': ['gim'],

    'in': ['in'],
    'hin': ['hin'],
    'pin': ['pin'],
    'phin': ['pʰin'],
    'bin': ['bin'],
    'tin': ['tin'],
    'thin': ['tʰin'],
    'lin': ['lin'],
    'tsin': ['tsin'],
    'tshin': ['tsʰin'],
    'jin': ['ʥin'],
    'sin': ['sin'],
    'kin': ['kin'],
    'khin': ['kʰin'],
    'gin': ['gin'],

    'ing': ['iŋ'],
    'hing': ['hiŋ'],
    'ping': ['piŋ'],
    'phing': ['pʰiŋ'],
    'bing': ['biŋ'],
    'ting': ['tiŋ'],
    'thing': ['tʰiŋ'],
    'ling': ['liŋ'],
    'tsing': ['tsiŋ'],
    'tshing': ['tsʰiŋ'],
    'sing': ['siŋ'],
    'king': ['kiŋ'],
    'khing': ['kʰiŋ'],
    'ging': ['giŋ'],

    'ip': ['ip̚'],
    'hip': ['hip̚'],
    'lip': ['lip̚'],
    'tsip': ['tsip̚'],
    'tship': ['tsʰip̚'],
    'jip': ['ʥip̚'],
    'sip': ['sip̚'],
    'kip': ['kip̚'],
    'khip': ['kʰip̚'],

    'it': ['it̚'],
    'hit': ['hit̚'],
    'pit': ['pit̚'],
    'phit': ['pʰit̚'],
    'bit': ['bit̚'],
    'tit': ['tit̚'],
    'thit': ['tʰit̚'],
    'lit': ['lit̚'],
    'tsit': ['tsit̚'],
    'tshit': ['tsʰit̚'],
    'jit': ['ʥit̚'],
    'sit': ['sit̚'],
    'kit': ['kit̚'],
    'khit': ['kʰit̚'],

    'ik': ['ik̚'],
    'hik': ['hik̚'],
    'pik': ['pik̚'],
    'phik': ['pʰik̚'],
    'bik': ['bik̚'],
    'tik': ['tik̚'],
    'thik': ['tʰik̚'],
    'lik': ['lik̚'],
    'tsik': ['tsik̚'],
    'tshik': ['tsʰik̚'],
    'jik': ['ʥik̚'],
    'sik': ['sik̚'],
    'kik': ['kik̚'],
    'khik': ['kʰik̚'],
    'gik': ['gik̚'],

    # 'ia' 行
    'ia': ['iɑ'],
    'hia': ['hiɑ'],
    'mia': ['miɑ'],
    'tia': ['tiɑ'],
    'thia': ['tʰiɑ'],
    'nia': ['niɑ'],
    'lia': ['liɑ'],
    'tsia': ['tsiɑ'],
    'tshia': ['tsʰiɑ'],
    'jia': ['ʥiɑ'],
    'sia': ['siɑ'],
    'kia': ['kiɑ'],
    'khia': ['kʰiɑ'],
    'gia': ['giɑ'],
    'ngia': ['ŋiɑ'],

    'iann': ['iɑ̃'],
    'hiann': ['hiɑ̃'],
    'piann': ['piɑ̃'],
    'phiann': ['pʰiɑ̃'],
    'tiann': ['tiɑ̃'],
    'thiann': ['tʰiɑ̃'],
    'tsiann': ['tsiɑ̃'],
    'tshiann': ['tsʰiɑ̃'],
    'siann': ['siɑ̃'],
    'kiann': ['kiɑ̃'],
    'khiann': ['kʰiɑ̃'],

    'iah': ['iɑʔ'],
    'hiah': ['hiɑʔ'],
    'piah': ['piɑʔ'],
    'phiah': ['pʰiɑʔ'],
    'tiah': ['tiɑʔ'],
    'thiah': ['tʰiɑʔ'],
    'liah': ['liɑʔ'],
    'tsiah': ['tsiɑʔ'],
    'tshiah': ['tsʰiɑʔ'],
    'jiah': ['ʥiɑʔ'],
    'siah': ['siɑʔ'],
    'kiah': ['kiɑʔ'],
    'khiah': ['kʰiɑʔ'],
    'giah': ['giɑʔ'],

    'iannh': ['iɑ̃ʔ'],
    'hiannh': ['hiɑ̃ʔ'],
    'siannh': ['siɑ̃ʔ'],

    'iam': ['iɑm'],
    'hiam': ['hiɑm'],
    'tiam': ['tiɑm'],
    'thiam': ['tʰiɑm'],
    'liam': ['liɑm'],
    'tsiam': ['tsiɑm'],
    'tshiam': ['tsʰiɑm'],
    'jiam': ['ʥiɑm'],
    'siam': ['siɑm'],
    'kiam': ['kiɑm'],
    'khiam': ['kʰiɑm'],
    'giam': ['giɑm'],

    'ian': ['iɑn'],
    'hian': ['hiɑn'],
    'pian': ['piɑn'],
    'phian': ['pʰiɑn'],
    'bian': ['biɑn'],
    'tian': ['tiɑn'],
    'thian': ['tʰiɑn'],
    'lian': ['liɑn'],
    'tsian': ['tsiɑn'],
    'tshian': ['tsʰiɑn'],
    'jian': ['ʥiɑn'],
    'sian': ['siɑn'],
    'kian': ['kiɑn'],
    'khian': ['kʰiɑn'],
    'gian': ['giɑn'],

    'iang': ['iɑŋ'],
    'hiang': ['hiɑŋ'],
    'piang': ['piɑŋ'],
    'phiang': ['pʰiɑŋ'],
    'liang': ['liɑŋ'],
    'tsiang': ['tsiɑŋ'],
    'tshiang': ['tsʰiɑŋ'],
    'jiang': ['ʥiɑŋ'],
    'siang': ['siɑŋ'],
    'kiang': ['kiɑŋ'],
    'khiang': ['kʰiɑŋ'],
    'giang': ['giɑŋ'],

    'iap': ['iɑp̚'],
    'hiap': ['hiɑp̚'],
    'tiap': ['tiɑp̚'],
    'thiap': ['tʰiɑp̚'],
    'liap': ['liɑp̚'],
    'tsiap': ['tsiɑp̚'],
    'tshiap': ['tsʰiɑp̚'],
    'jiap': ['ʥiɑp̚'],
    'siap': ['siɑp̚'],
    'kiap': ['kiɑp̚'],
    'khiap': ['kʰiɑp̚'],
    'giap': ['giɑp̚'],

    'iat': ['iɑt̚'],
    'hiat': ['hiɑt̚'],
    'piat': ['piɑt̚'],
    'phiat': ['pʰiɑt̚'],
    'biat': ['biɑt̚'],
    'tiat': ['tiɑt̚'],
    'thiat': ['tʰiɑt̚'],
    'liat': ['liɑt̚'],
    'tsiat': ['tsiɑt̚'],
    'tshiat': ['tsʰiɑt̚'],
    'jiat': ['ʥiɑt̚'],
    'siat': ['siɑt̚'],
    'kiat': ['kiɑt̚'],
    'khiat': ['kʰiɑt̚'],
    'giat': ['giɑt̚'],

    'iak': ['iɑk̚'],
    'piak': ['piɑk̚'],
    'phiak': ['pʰiɑk̚'],
    'tiak': ['tiɑk̚'],
    'tshiak': ['tsʰiɑk̚'],
    'siak': ['siɑk̚'],
    'khiak': ['kʰiɑk̚'],

    'iau': ['iɑu'],
    'hiau': ['hiɑu'],
    'piau': ['piɑu'],
    'phiau': ['pʰiɑu'],
    'biau': ['biɑu'],
    'miau': ['miɑu'],
    'tiau': ['tiɑu'],
    'thiau': ['tʰiɑu'],
    'niau': ['niɑu'],
    'liau': ['liɑu'],
    'tsiau': ['tsiɑu'],
    'tshiau': ['tsʰiɑu'],
    'jiau': ['ʥiɑu'],
    'siau': ['siɑu'],
    'kiau': ['kiɑu'],
    'khiau': ['kʰiɑu'],
    'giau': ['giɑu'],
    'ngiau': ['ŋiɑu'],

    'iauh': ['iɑuʔ'],
    'hiauh': ['hiɑuʔ'],
    'khiauh': ['kʰiɑuʔ'],
    'ngiauh': ['ŋiɑuʔ'],

    # 'io' 行
    'io': ['iə'],
    'hio': ['hiə'],
    'pio': ['piə'],
    'phio': ['pʰiə'],
    'bio': ['biə'],
    'tio': ['tiə'],
    'thio': ['tʰiə'],
    'lio': ['liə'],
    'tsio': ['tsiə'],
    'tshio': ['tsʰiə'],
    'jio': ['ʥiə'],
    'sio': ['siə'],
    'kio': ['kiə'],
    'khio': ['kʰiə'],
    'gio': ['giə'],

    'ionn': ['iɔ̃'],
    'hionn': ['hiɔ̃'],
    'tionn': ['tiɔ̃'],
    'tsionn': ['tsiɔ̃'],
    'tshionn': ['tsʰiɔ̃'],
    'sionn': ['siɔ̃'],
    'kionn': ['kiɔ̃'],
    'khionn': ['kʰiɔ̃'],

    'ioh': ['iəʔ'],
    'hioh': ['hiəʔ'],
    'tioh': ['tiəʔ'],
    'lioh': ['liəʔ'],
    'tsioh': ['tsiəʔ'],
    'tshioh': ['tsʰiəʔ'],
    'sioh': ['siəʔ'],
    'kioh': ['kiəʔ'],
    'khioh': ['kʰiəʔ'],
    'gioh': ['giəʔ'],

    'iong': ['iɔŋ'],
    'hiong': ['hiɔŋ'],
    'tiong': ['tiɔŋ'],
    'thiong': ['tʰiɔŋ'],
    'liong': ['liɔŋ'],
    'tsiong': ['tsiɔŋ'],
    'tshiong': ['tsʰiɔŋ'],
    'jiong': ['ʥiɔŋ'],
    'siong': ['siɔŋ'],
    'kiong': ['kiɔŋ'],
    'khiong': ['kʰiɔŋ'],
    'giong': ['giɔŋ'],
    

    'iok': ['iɔk̚'],
    'hiok': ['hiɔk̚'],
    'tiok': ['tiɔk̚'],
    'thiok': ['tʰiɔk̚'],
    'liok': ['liɔk̚'],
    'tsiok': ['tsiɔk̚'],
    'tshiok': ['tsʰiɔk̚'],
    'jiok': ['ʥiɔk̚'],
    'siok': ['siɔk̚'],
    'kiok': ['kiɔk̚'],
    'khiok': ['kʰiɔk̚'],
    'giok': ['giɔk̚'],

    # 'iu' 行
    'iu': ['iu'],
    'hiu': ['hiu'],
    'piu': ['piu'],
    'biu': ['biu'],
    'tiu': ['tiu'],
    'thiu': ['tʰiu'],
    'niu': ['niu'],
    'liu': ['liu'],
    'tsiu': ['tsiu'],
    'tshiu': ['tsʰiu'],
    'jiu': ['ʥiu'],
    'siu': ['siu'],
    'kiu': ['kiu'],
    'khiu': ['kʰiu'],
    'giu': ['giu'],
    'ngiu': ['ŋiu'],

    'iunn': ['iũ'],
    'hiunn': ['hiũ'],
    'tiunn': ['tiũ'],
    'tsiunn': ['tsiũ'],
    'tshiunn': ['tsʰiũ'],
    'siunn': ['siũ'],
    'kiunn': ['kiũ'],
    'khiunn': ['kʰiũ'],

    'iunnh': ['iũʔ'],
    'hiunnh': ['hiũʔ'],

    'iunnhh': ['iũʔʔ'],

    # 'u' 行
    'u': ['u'],
    'hu': ['hu'],
    'pu': ['pu'],
    'phu': ['pʰu'],
    'bu': ['bu'],
    'tu': ['tu'],
    'thu': ['tʰu'],
    'lu': ['lu'],
    'tsu': ['tsu'],
    'tshu': ['tsʰu'],
    'ju': ['ʥu'],
    'su': ['su'],
    'ku': ['ku'],
    'khu': ['kʰu'],
    'gu': ['gu'],

    'uh': ['uʔ'],
    'puh': ['puʔ'],
    'phuh': ['pʰuʔ'],
    'buh': ['buʔ'],
    'tuh': ['tuʔ'],
    'thuh': ['tʰuʔ'],
    'luh': ['luʔ'],
    'tsuh': ['tsuʔ'],
    'tshuh': ['tsʰuʔ'],
    'suh': ['suʔ'],
    'khuh': ['kʰuʔ'],

    'un': ['un'],
    'hun': ['hun'],
    'pun': ['pun'],
    'phun': ['pʰun'],
    'bun': ['bun'],
    'tun': ['tun'],
    'thun': ['tʰun'],
    'lun': ['lun'],
    'tsun': ['tsun'],
    'tshun': ['tsʰun'],
    'jun': ['ʥun'],
    'sun': ['sun'],
    'kun': ['kun'],
    'khun': ['kʰun'],
    'gun': ['gun'],

    'ut': ['ut̚'],
    'hut': ['hut̚'],
    'put': ['put̚'],
    'phut': ['pʰut̚'],
    'but': ['but̚'],
    'tut': ['tut̚'],
    'thut': ['tʰut̚'],
    'lut': ['lut̚'],
    'tsut': ['tsut̚'],
    'tshut': ['tsʰut̚'],
    'sut': ['sut̚'],
    'kut': ['kut̚'],
    'khut': ['kʰut̚'],

    'ua': ['uɑ'],
    'hua': ['huɑ'],
    'pua': ['puɑ'],
    'phua': ['pʰuɑ'],
    'bua': ['buɑ'],
    'mua': ['muɑ'],
    'tua': ['tuɑ'],
    'thua': ['tʰuɑ'],
    'nua': ['nuɑ'],
    'lua': ['luɑ'],
    'tsua': ['tsuɑ'],
    'tshua': ['tsʰuɑ'],
    'jua': ['ʥuɑ'],
    'sua': ['suɑ'],
    'kua': ['kuɑ'],
    'khua': ['kʰuɑ'],
    'gua': ['guɑ'],

    'uann': ['uɑ̃'],
    'huann': ['huɑ̃'],
    'puann': ['puɑ̃'],
    'phuann': ['pʰuɑ̃'],
    'tuann': ['tuɑ̃'],
    'thuann': ['tʰuɑ̃'],
    'tsuann': ['tsuɑ̃'],
    'tshuann': ['tsʰuɑ̃'],
    'suann': ['suɑ̃'],
    'kuann': ['kuɑ̃'],
    'khuann': ['kʰuɑ̃'],

    'uah': ['uɑʔ'],
    'huah': ['huɑʔ'],
    'puah': ['puɑʔ'],
    'phuah': ['pʰuɑʔ'],
    'buah': ['buɑʔ'],
    'tuah': ['tuɑʔ'],
    'thuah': ['tʰuɑʔ'],
    'luah': ['luɑʔ'],
    'tsuah': ['tsuɑʔ'],
    'tshuah': ['tsʰuɑʔ'],
    'juah': ['ʥuɑʔ'],
    'suah': ['suɑʔ'],
    'kuah': ['kuɑʔ'],
    'khuah': ['kʰuɑʔ'],

    'uan': ['uɑn'],
    'huan': ['huɑn'],
    'puan': ['puɑn'],
    'phuan': ['pʰuɑn'],
    'buan': ['buɑn'],
    'tuan': ['tuɑn'],
    'thuan': ['tʰuɑn'],
    'luan': ['luɑn'],
    'tsuan': ['tsuɑn'],
    'tshuan': ['tsʰuɑn'],
    'suan': ['suɑn'],
    'kuan': ['kuɑn'],
    'khuan': ['kʰuɑn'],
    'guan': ['guɑn'],

    'uang': ['uɑŋ'],
    'huang': ['huɑŋ'],
    'tshuang': ['tsʰuɑŋ'],

    'uat': ['uɑt̚'],
    'huat': ['huɑt̚'],
    'puat': ['puɑt̚'],
    'phuat': ['pʰuɑt̚'],
    'buat': ['buɑt̚'],
    'tuat': ['tuɑt̚'],
    'thuat': ['tʰuɑt̚'],
    'luat': ['luɑt̚'],
    'tsuat': ['tsuɑt̚'],
    'suat': ['suɑt̚'],
    'kuat': ['kuɑt̚'],
    'khuat': ['kʰuɑt̚'],
    'guat': ['guɑt̚'],

    'uai': ['uɑɪ'],
    'huai': ['huɑɪ'],
    'suai': ['suɑɪ'],
    'kuai': ['kuɑɪ'],
    'khuai': ['kʰuɑɪ'],

    'uainn': ['uɑ̃ɪ'],
    'huainn': ['huɑ̃ɪ'],
    'tsuainn': ['tsuɑ̃ɪ'],
    'suainn': ['suɑ̃ɪ'],
    'kuainn': ['kuɑ̃ɪ'],

    'uaih': ['uɑɪʔ'],
    'buaih': ['buɑɪʔ'],
    'luaih': ['luɑɪʔ'],
    'tshuaih': ['tsʰuɑɪʔ'],
    'kuaih': ['kuɑɪʔ'],

    'uainnh': ['uɑ̃ɪʔ'],
    'kuainnh': ['kuɑ̃ɪʔ'],

    # 'ue' 行
    'ue': ['ue'],
    'hue': ['hue'],
    'pue': ['pue'],
    'phue': ['pʰue'],
    'bue': ['bue'],
    'mue': ['mue'],
    'tue': ['tue'],
    'thue': ['tʰue'],
    'lue': ['lue'],
    'tsue': ['tsue'],
    'tshue': ['tsʰue'],
    'jue': ['ʥue'],
    'sue': ['sue'],
    'kue': ['kue'],
    'khue': ['kʰue'],
    'gue': ['gue'],

    'ueh': ['ueʔ'],
    'hueh': ['hueʔ'],
    'pueh': ['pueʔ'],
    'phueh': ['pʰueʔ'],
    'bueh': ['bueʔ'],
    'thueh': ['tʰueʔ'],
    'lueh': ['lueʔ'],
    'tsueh': ['tsueʔ'],
    'tshueh': ['tsʰueʔ'],
    'sueh': ['sueʔ'],
    'kueh': ['kueʔ'],
    'khueh': ['kʰueʔ'],
    'gueh': ['gueʔ'],
    'ngueh': ['ŋueʔ'],

    'ui': ['ui'],
    'hui': ['hui'],
    'pui': ['pui'],
    'phui': ['pʰui'],
    'bui': ['bui'],
    'mui': ['mui'],
    'tui': ['tui'],
    'thui': ['tʰui'],
    'lui': ['lui'],
    'tsui': ['tsui'],
    'tshui': ['tsʰui'],
    'jui': ['ʥui'],
    'sui': ['sui'],
    'kui': ['kui'],
    'khui': ['kʰui'],
    'gui': ['gui'],

    'uinn': ['ũi'],
    'huinn': ['hũi'],
    'puinn': ['pũi'],
    'suinn': ['sũi'],
    'kuinn': ['kũi'],

    'uih': ['uiʔ'],
    'huih': ['huiʔ'],
    'kuih': ['kuiʔ'],

    # 'm̩' 行
    'm': ['m̩'],
    'hm': ['hm̩'],

    'mh': ['m̩ʔ'],
    'hmh': ['hm̩ʔ'],

    # 'ŋ̍' 行
    'ng': ['ŋ̍'],
    'hng': ['hŋ̍'],
    'png': ['pŋ̍'],
    'mng': ['mŋ̍'],
    'tng': ['tŋ̍'],
    'thng': ['tʰŋ̍'],
    'nng': ['nŋ̍'],
    'tsng': ['tsŋ̍'],
    'tshng': ['tsʰŋ̍'],
    'sng': ['sŋ̍'],
    'kng': ['kŋ̍'],
    'khng': ['kʰŋ̍'],

    'ngh': ['ŋ̍ʔ'],
    'hngh': ['hŋ̍ʔ'],
    'phngh': ['pʰŋ̍ʔ'],
    'mngh': ['mŋ̍ʔ'],
    'tshngh': ['tsʰŋ̍ʔ'],
    'sngh': ['sŋ̍ʔ'],
    'khngh': ['kʰŋ̍ʔ'],
    
      # 'iong' の欠けていたエントリを追加
    'iongh': ['iɔŋʔ'],
    'hiongh': ['hiɔŋʔ'],
    'tiongh': ['tiɔŋʔ'],
    'thiongh': ['tʰiɔŋʔ'],
    'liongh': ['liɔŋʔ'],
    'tsiongh': ['tsiɔŋʔ'],
    'tshiongh': ['tsʰiɔŋʔ'],
    'jiongh': ['ʥiɔŋʔ'],
    'siongh': ['siɔŋʔ'],
    'kiongh': ['kiɔŋʔ'],
    'khiongh': ['kʰiɔŋʔ'],
    'giongh': ['giɔŋʔ'],
    
    # 'iau' 行の欠けていたエントリを追加
    'iaunn': ['iɑ̃u'],
    'hiaunn': ['hiɑ̃u'],
    'tshiaunn': ['tsʰiɑ̃u'],
    'kiaunn': ['kiɑ̃u'],
    'khiaunn': ['kʰiɑ̃u'],
    
    # 'iau' 行の欠けていたエントリ
    'piauh': ['piɑuʔ'],
    'phiauh': ['pʰiɑuʔ'],
    'tiauh': ['tiɑuʔ'],
    'thiauh': ['tʰiɑuʔ'],
    'liauh': ['liɑuʔ'],
    'tsiauh': ['tsiɑuʔ'],
    'tshiauh': ['tsʰiɑuʔ'],
    'jiauh': ['ʥiɑuʔ'],
    'siauh': ['siɑuʔ'],
    'kiauh': ['kiɑuʔ'],
    'giauh': ['giɑuʔ'],

    # 'u' 行の欠けていたエントリを追加
    'nguh': ['ŋuʔ'],

    # 'un' 行の欠けていたエントリを追加
    'nun': ['nun'],
    'ngun': ['ŋun'],

    # 'ut' 行の欠けていたエントリを追加
    'ngut': ['ŋut̚'],

    # 'o' 行の欠けていたエントリを追加
    'o': ['ə'],
    'ho': ['hə'],
    'po': ['pə'],
    'pho': ['pʰə'],
    'bo': ['bə'],
    'to': ['tə'],
    'tho': ['tʰə'],
    'lo': ['lə'],
    'tso': ['tsə'],
    'tsho': ['tsʰə'],
    'so': ['sə'],
    'ko': ['kə'],
    'kho': ['kʰə'],
    'go': ['gə'],
    
    
     # 'oo' 行の欠けていたエントリを追加
    'oo': ['ɔ'],
    'hoo': ['hɔ'],
    'poo': ['pɔ'],
    'phoo': ['pʰɔ'],
    'boo': ['bɔ'],
    'moo': ['mɔ'],
    'too': ['tɔ'],
    'thoo': ['tʰɔ'],
    'noo': ['nɔ'],
    'loo': ['lɔ'],
    'tsoo': ['tsɔ'],
    'tshoo': ['tsʰɔ'],
    'soo': ['sɔ'],
    'koo': ['kɔ'],
    'khoo': ['kʰɔ'],
    'goo': ['gɔ'],
    'ngoo': ['ŋɔ'],
    
    # 'oo' 行の鼻音化エントリ
    'oonn': ['ɔ̃'],
    'hoonn': ['hɔ̃'],
    'toonn': ['tɔ̃'],
    'thoonn': ['tʰɔ̃'],
    'loonn': ['lɔ̃'],
    'soon': ['sɔ̃'],
    'koonn': ['kɔ̃'],
    'khoonn': ['kʰɔ̃'],
    
    # 追加のエントリ:

# 'au' 行の欠けていたエントリ
'hauann': ['hɑ̃u'],
'pauann': ['pɑ̃u'],
'phauann': ['pʰɑ̃u'],
'bauann': ['bɑ̃u'],
'mauann': ['mɑ̃u'],
'thauann': ['tʰɑ̃u'],
'nauann': ['nɑ̃u'],
'khauann': ['kʰɑ̃u'],
'gauann': ['gɑ̃u'],
'ngauann': ['ŋɑ̃u'],

# 'auh' 行の欠けていたエントリ
'hauh': ['hɑuʔ'],
'pauh': ['pɑuʔ'],
'thauh': ['tʰɑuʔ'],
'tsauh': ['tsɑuʔ'],
'sauh': ['sɑuʔ'],
'khauh': ['kʰɑuʔ'],
'gauh': ['gɑuʔ'],

# 'iau' 行の欠けていたエントリ
'niauh': ['niɑuʔ'],
'miauh': ['miɑuʔ'],

# 'iau' 行の欠けていた鼻音化エントリ
'iaunnh': ['iɑ̃uʔ'],
'hiaunnh': ['hiɑ̃uʔ'],
'kiaunnh': ['kiɑ̃uʔ'],
'khiaunnh': ['kʰiɑ̃uʔ'],

# 'ian' 行の欠けていたエントリ
'nian': ['niɑn'],
'niann': ['niɑ̃'],
'niannh': ['niɑ̃ʔ'],

# 'iam' 行の欠けていたエントリ
'niam': ['niɑm'],

# 'iang' 行の欠けていたエントリ
'niang': ['niɑŋ'],

# 'u' 行の欠けていたエントリ
'ngu': ['ŋu'],

# 'uh' 行の欠けていたエントリ
'huh': ['huʔ'],
'nguh': ['ŋuʔ'],

# 'un' 行の欠けていたエントリ
'ngun': ['ŋun'],
'nun': ['nun'],

# 'ut' 行の欠けていたエントリ
'ngut': ['ŋut̚'],
'nut': ['nut̚'],

# 'ua' 行の欠けていたエントリ
'nua': ['nuɑ'],

# 'uann' 行の欠けていたエントリ
'nuann': ['nuɑ̃'],
'nguann': ['ŋuɑ̃'],

# 'uah' 行の欠けていたエントリ
'nuah': ['nuɑʔ'],
'nguah': ['ŋuɑʔ'],

# 'uan' 行の欠けていたエントリ
'nuan': ['nuɑn'],
'nguan': ['ŋuɑn'],

# 'uat' 行の欠けていたエントリ
'nuat': ['nuɑt̚'],

# 'uang' 行の欠けていたエントリ
'kuang': ['kuɑŋ'],
'khuang': ['kʰuɑŋ'],
'guang': ['guɑŋ'],
'nguang': ['ŋuɑŋ'],

# 'uai' 行の欠けていたエントリ
'tuai': ['tuɑɪ'],
'thuai': ['tʰuɑɪ'],
'luai': ['luɑɪ'],
'guai': ['guɑɪ'],
'nguai': ['ŋuɑɪ'],

# 'uaih' 行の欠けていたエントリ
'suaih': ['suɑɪʔ'],
'huaih': ['huɑɪʔ'],

# 'uainn' 行の欠けていたエントリ
'guainn': ['guɑ̃ɪ'],
'nguainn': ['ŋuɑ̃ɪ'],

# 'uainnh' 行の欠けていたエントリ
'huainnh': ['huɑ̃ɪʔ'],

# 'ue' 行の欠けていたエントリ
'nue': ['nue'],
'ngue': ['ŋue'],

# 'ueh' 行の欠けていたエントリ
'nueh': ['nueʔ'],

# 'ui' 行の欠けていたエントリ
'nui': ['nui'],
'ngui': ['ŋui'],

# 'uih' 行の欠けていたエントリ
'puih': ['puiʔ'],
'phuih': ['pʰuiʔ'],
'buih': ['buiʔ'],
'muih': ['muiʔ'],
'tuih': ['tuiʔ'],
'thuih': ['tʰuiʔ'],
'luih': ['luiʔ'],
'suih': ['suiʔ'],
'kuih': ['kuiʔ'],
'khuih': ['kʰuiʔ'],
'guih': ['guiʔ'],
'nguih': ['ŋuiʔ'],

# 'o' 行の欠けていたエントリ
'no': ['nə'],
'mo': ['mə'],

# 'oh' 行の欠けていたエントリ
'noh': ['nəʔ'],
'moh': ['məʔ'],

# 'oo' 行の欠けていたエントリ
'noo': ['nɔ'],
'nooh': ['nɔʔ'],

# 'oonn' 行の欠けていたエントリ
'noonn': ['nɔ̃'],
'moonn': ['mɔ̃'],

# 'oonnh' 行の欠けていたエントリ
'oonnh': ['ɔ̃ʔ'],
'hoonnh': ['hɔ̃ʔ'],
'koonnh': ['kɔ̃ʔ'],
'khoonnh': ['kʰɔ̃ʔ'],
'goonnh': ['gɔ̃ʔ'],
'ngoonnh': ['ŋɔ̃ʔ'],

# 'im' 行の欠けていたエントリ
'nim': ['nim'],

# 'in' 行の欠けていたエントリ
'nin': ['nin'],

# 'ing' 行の欠けていたエントリ
'ning': ['niŋ'],

# 'iat' 行の欠けていたエントリ
'niat': ['niɑt̚'],
'niap': ['niɑp̚'],

# 'iang' 行の欠けていたエントリ
'niang': ['niɑŋ'],

# 'io' 行の欠けていたエントリ
'nio': ['niə'],
'nioh': ['niəʔ'],
'niong': ['niɔŋ'],
'niok': ['niɔk̚'],

# 'iu' 行の欠けていたエントリ
'miu': ['miu'],

# 'iunn' 行の欠けていたエントリ
'miunn': ['miũ'],
'niunn': ['niũ'],

# 'iunnh' 行の欠けていたエントリ
'kiunnh': ['kiũʔ'],
'khiunnh': ['kʰiũʔ'],
'giunnh': ['giũʔ'],

# 'm̩' 行の欠けていたエントリ
'mm': ['m̩m'],
'mmh': ['m̩mʔ'],

# 'ŋ̍' 行の欠けていたエントリ
'nng': ['nŋ̍'],
'nngh': ['nŋ̍ʔ'],

# 'iong' 行の欠けていたエントリ
'niong': ['niɔŋ'],
'niongh': ['niɔŋʔ'],

# 'ngia' 行の欠けていたエントリ
'ngiam': ['ŋiɑm'],
'ngian': ['ŋiɑn'],
'ngiang': ['ŋiɑŋ'],
'ngiap': ['ŋiɑp̚'],
'ngiat': ['ŋiɑt̚'],

# 'unnh' 行の欠けていたエントリ
'unnh': ['ũʔ'],
'hunnh': ['hũʔ'],
'kunnh': ['kũʔ'],
'khunnh': ['kʰũʔ'],
'gunnh': ['gũʔ'],

# 'uinn' 行の欠けていたエントリ
'nuinn': ['nũi'],
'guinn': ['gũi'],
'nguinn': ['ŋũi'],

# 'uinnh' 行の欠けていたエントリ
'uinnh': ['ũiʔ'],
'huinnh': ['hũiʔ'],
'kuinnh': ['kũiʔ'],
'khuinnh': ['kʰũiʔ'],

# 'uih' 行の欠けていたエントリ
'nuih': ['nuiʔ'],

# 'ueh' 行の欠けていたエントリ
'mueh': ['mueʔ'],
'newueh': ['nueʔ'],

# 'ue' 行の欠けていたエントリ
'nue': ['nue'],
'ngue': ['ŋue'],
'mueh': ['mueʔ'],

# 'ueh' 行の欠けていたエントリ
'kueh': ['kueʔ'],
'khueh': ['kʰueʔ'],
'gueh': ['gueʔ'],

# 'ua' 行の欠けていたエントリ
'nuai': ['nuɑɪ'],
'nuaih': ['nuɑɪʔ'],
'nuainn': ['nuɑ̃ɪ'],
'nuainnh': ['nuɑ̃ɪʔ'],
'nguai': ['ŋuɑɪ'],
'nguaih': ['ŋuɑɪʔ'],
'nguainn': ['ŋuɑ̃ɪ'],
'nguainnh': ['ŋuɑ̃ɪʔ'],

# 追加のエントリ:

# 'a' 行の欠けていたエントリ
'ngak': ['ŋɑk̚'],

# 'aih' 行の欠けていたエントリ
'ngaih': ['ŋɑɪʔ'],

# 'ih' 行の欠けていたエントリ
'ngih': ['ŋiʔ'],

# 'im' 行の欠けていたエントリ
'ngim': ['ŋim'],

# 'in' 行の欠けていたエントリ
'ngin': ['ŋin'],

# 'ip' 行の欠けていたエントリ
'ngip': ['ŋip̚'],

# 'it' 行の欠けていたエントリ
'ngit': ['ŋit̚'],

# 'ik' 行の欠けていたエントリ
'ngik': ['ŋik̚'],

# 'iann' 行の欠けていたエントリ
'ngiann': ['ŋiɑ̃'],

# 'iah' 行の欠けていたエントリ
'ngiah': ['ŋiɑʔ'],

# 'iannh' 行の欠けていたエントリ
'ngiannh': ['ŋiɑ̃ʔ'],

# 'iak' 行の欠けていたエントリ
'ngiak': ['ŋiɑk̚'],

# 'io' 行の欠けていたエントリ
'ngio': ['ŋiə'],

# 'ioh' 行の欠けていたエントリ
'ngioh': ['ŋiəʔ'],

# 'iong' 行の欠けていたエントリ
'ngiong': ['ŋiɔŋ'],

# 'iok' 行の欠けていたエントリ
'ngiok': ['ŋiɔk̚'],

# 'iunn' 行の欠けていたエントリ
'ngiunn': ['ŋiũ'],

# 'iunnh' 行の欠けていたエントリ
'ngiunnh': ['ŋiũʔ'],

# 'o' 行の欠けていたエントリ
'ngo': ['ŋə'],

# 'oh' 行の欠けていたエントリ
'ngoh': ['ŋəʔ'],

# 'ua' 行の欠けていたエントリ
'ngua': ['ŋuɑ'],

# 'ong' 行の欠けていたエントリ
'ngong': ['ŋɔŋ'],

# 'ok' 行の欠けていたエントリ
'ngok': ['ŋɔk̚'],

# 'om' 行の欠けていたエントリ
'ngom': ['ŋɔm'],

# 'op' 行の欠けていたエントリ
'ngop': ['ŋɔp̚'],

# 追加のエントリ:

# 'ang' 行の欠けていたエントリ
'ngang': ['ŋɑŋ'],

# 'ap' 行の欠けていたエントリ
'ngap': ['ŋɑp̚'],

# 'at' 行の欠けていたエントリ
'ngat': ['ŋɑt̚'],

# 'ong' 行の欠けていたエントリ
'ong': ['ɔŋ'],
'hong': ['hɔŋ'],
'pong': ['pɔŋ'],
'phong': ['pʰɔŋ'],
'bong': ['bɔŋ'],
'mong': ['mɔŋ'],
'tong': ['tɔŋ'],
'thong': ['tʰɔŋ'],
'nong': ['nɔŋ'],
'long': ['lɔŋ'],
'tsong': ['tsɔŋ'],
'tshong': ['tsʰɔŋ'],
'song': ['sɔŋ'],
'kong': ['kɔŋ'],
'khong': ['kʰɔŋ'],
'gong': ['gɔŋ'],
'ngong': ['ŋɔŋ'],

# 'ok' 行の欠けていたエントリ
'ok': ['ɔk̚'],
'hok': ['hɔk̚'],
'pok': ['pɔk̚'],
'phok': ['pʰɔk̚'],
'bok': ['bɔk̚'],
'mok': ['mɔk̚'],
'tok': ['tɔk̚'],
'thok': ['tʰɔk̚'],
'nok': ['nɔk̚'],
'lok': ['lɔk̚'],
'tsok': ['tsɔk̚'],
'tshok': ['tsʰɔk̚'],
'sok': ['sɔk̚'],
'kok': ['kɔk̚'],
'khok': ['kʰɔk̚'],
'gok': ['gɔk̚'],
'ngok': ['ŋɔk̚'],

# 'on' 行の欠けていたエントリ
'on': ['ɔn'],
'hon': ['hɔn'],
'pon': ['pɔn'],
'phon': ['pʰɔn'],
'bon': ['bɔn'],
'mon': ['mɔn'],
'ton': ['tɔn'],
'thon': ['tʰɔn'],
'non': ['nɔn'],
'lon': ['lɔn'],
'tson': ['tsɔn'],
'tshon': ['tsʰɔn'],
'son': ['sɔn'],
'kon': ['kɔn'],
'khon': ['kʰɔn'],
'gon': ['gɔn'],
'ngon': ['ŋɔn'],

# 'onh' 行の欠けていたエントリ
'onh': ['ɔ̃ʔ'],
'honh': ['hɔ̃ʔ'],
'ponh': ['pɔ̃ʔ'],
'phonh': ['pʰɔ̃ʔ'],
'bonh': ['bɔ̃ʔ'],
'monh': ['mɔ̃ʔ'],
'tonh': ['tɔ̃ʔ'],
'thonh': ['tʰɔ̃ʔ'],
'nonh': ['nɔ̃ʔ'],
'lonh': ['lɔ̃ʔ'],
'tsonh': ['tsɔ̃ʔ'],
'tshonh': ['tsʰɔ̃ʔ'],
'sonh': ['sɔ̃ʔ'],
'konh': ['kɔ̃ʔ'],
'khonh': ['kʰɔ̃ʔ'],
'gonh': ['gɔ̃ʔ'],
'ngonh': ['ŋɔ̃ʔ'],

# 追加のエントリ:

# 'boe' 行
'boe': ['bue'],

# 'eng' 行
'eng': ['eŋ'],

# 'hn̄g' 行
'hn̄g': ['hŋ̍'],

# 'honnh' 行
'honnh': ['hə̃ʔ'],

# 'hooh' 行
'hooh': ['hɔʔ'],

# 'khaunnh' 行
'khaunnh': ['kʰɑ̃uʔ'],

# 'khuinn' 行
'khuinn': ['kʰũi'],

# 'khǹg' 行
'khǹg': ['kʰŋ̍ʔ'],

# 'koh' 行
'koh': ['kəʔ'],

# 'kǹg' 行
'kǹg': ['kŋ̍ʔ'],

# 'loh' 行
'loh': ['ləʔ'],

# 'mn̄g' 行
'mn̄g': ['mŋ̍'],

# 'mooh' 行
'mooh': ['mɔʔ'],

# 'm̂' 行
'm̂': ['m̩̃'],

# 'm̄' 行
'm̄': ['m̩'],

# 'nn̄g' 行
'nn̄g': ['nŋ̍'],

# 'n̄g' 行
'n̄g': ['ŋ̍'],

# 'oan' 行
'oan': ['uɑn'],

# 'oh' 行
'oh': ['əʔ'],

# 'onn' 行
'onn': ['ə̃'],

# 'ooh' 行
'ooh': ['ɔʔ'],

# 'phoh' 行
'phoh': ['pʰəʔ'],

# 'pn̄g' 行
'pn̄g': ['pŋ̍'],

# 'poh' 行
'poh': ['pəʔ'],

# 'soh' 行
'soh': ['səʔ'],

# 'sǹg' 行
'sǹg': ['sŋ̍ʔ'],

# 'thn̄g' 行
'thn̄g': ['tʰŋ̍'],

# 'thoh' 行
'thoh': ['tʰəʔ'],

# 'thǹg' 行
'thǹg': ['tʰŋ̍ʔ'],

# 'tiuh' 行
'tiuh': ['tiuʔ'],

# 'tn̄g' 行
'tn̄g': ['tŋ̍'],

# 'toh' 行
'toh': ['təʔ'],

# 'tom' 行
'tom': ['təm'],

# 'tshǹg' 行
'tshǹg': ['tsʰŋ̍ʔ'],

# 'tsn̄g' 行
'tsn̄g': ['tsŋ̍'],

# 'tsoh' 行
'tsoh': ['tsəʔ'],

# 'tsǹg' 行
'tsǹg': ['tsŋ̍ʔ'],

# 'tǹg' 行
'tǹg': ['tŋ̍ʔ'],


    # とりあえず追加
    'a': ['ɑ'],
    'ha': ['hɑ'],
    'pa': ['pɑ'],
    'pha': ['pʰɑ'],
    'ba': ['bɑ'],
    'ma': ['mɑ'],
    'ta': ['tɑ'],
    'tha': ['tʰɑ'],
    'na': ['nɑ'],
    'la': ['lɑ'],
    'tsa': ['ʦɑ'],
    'tsha': ['ʦʰɑ'],
    'sa': ['sɑ'],
    'ka': ['kɑ'],
    'kha': ['kʰɑ'],
    'ga': ['gɑ'],
    'nga': ['ŋɑ'],
    'ã': ['ã'],
    'hann': ['hɑ̃'],
    'pah': ['pɑʔ'],
    'phah': ['pʰɑʔ'],
    'bah': ['bɑʔ'],
    'mah': ['mɑʔ'],
    'tah': ['tɑʔ'],
    'thah': ['tʰɑʔ'],
    'nah': ['nɑʔ'],
    'lah': ['lɑʔ'],
    'tsah': ['ʦɑʔ'],
    'tshah': ['ʦʰɑʔ'],
    'sah': ['sɑʔ'],
    'kah': ['kɑʔ'],
    'khah': ['kʰɑʔ'],
    'gam': ['gɑm'],
    'tam': ['tɑm'],
    'tham': ['tʰɑm'],
    'lam': ['lɑm'],
    'tsam': ['ʦɑm'],
    'tsham': ['ʦʰɑm'],
    'sam': ['sɑm'],
    'kam': ['kɑm'],
    'kham': ['kʰɑm'],
    'gang': ['gɑŋ'],
    'tang': ['tɑŋ'],
    'thang': ['tʰɑŋ'],
    'lang': ['lɑŋ'],
    'tsang': ['ʦɑŋ'],
    'tshang': ['ʦʰɑŋ'],
    'sang': ['sɑŋ'],
    'kang': ['kɑŋ'],
    'khang': ['kʰɑŋ'],
    'gah': ['gɑʔ'],
    'tap': ['tɑp̚'],
    'thap': ['tʰɑp̚'],
    'lap': ['lɑp̚'],
    'tsap': ['ʦɑp̚'],
    'tshap': ['ʦʰɑp̚'],
    'sap': ['sɑp̚'],
    'kap': ['kɑp̚'],
    'khap': ['kʰɑp̚'],
    'gat': ['gɑt̚'],
    'tat': ['tɑt̚'],
    'that': ['tʰɑt̚'],
    'lat': ['lɑt̚'],
    'tsat': ['ʦɑt̚'],
    'tshat': ['ʦʰɑt̚'],
    'sat': ['sɑt̚'],
    'kat': ['kɑt̚'],
    'khat': ['kʰɑt̚'],
    'gat': ['gɑt̚'],
    'ai': ['ɑi'],
    'hai': ['hɑi'],
    'pai': ['pɑi'],
    'phai': ['pʰɑi'],
    'bai': ['bɑi'],
    'mai': ['mɑi'],
    'tai': ['tɑi'],
    'thai': ['tʰɑi'],
    'nai': ['nɑi'],
    'lai': ['lɑi'],
    'tsai': ['ʦɑi'],
    'tshai': ['ʦʰɑi'],
    'sai': ['sɑi'],
    'kai': ['kɑi'],
    'khai': ['kʰɑi'],
    'gai': ['gɑi'],
    'ngai': ['ŋɑi'],
    'ainn': ['ɑĩ'],
    'hainn': ['hɑĩ'],
    'phainn': ['pʰɑĩ'],
    'bainn': ['bɑĩ'],
    'paih': ['pɑiʔ'],
    'phaih': ['pʰɑiʔ'],
    'baih': ['bɑiʔ'],
    'taih': ['tɑiʔ'],
    'thaih': ['tʰɑiʔ'],
    'saih': ['sɑiʔ'],
    'kaih': ['kɑiʔ'],
    'khaih': ['kʰɑiʔ'],
    'ngaih': ['ŋɑiʔ'],
    'au': ['ɑu'],
    'hau': ['hɑu'],
    'pau': ['pɑu'],
    'phau': ['pʰɑu'],
    'bau': ['bɑu'],
    'mau': ['mɑu'],
    'tau': ['tɑu'],
    'thau': ['tʰɑu'],
    'nau': ['nɑu'],
    'lau': ['lɑu'],
    'tsau': ['ʦɑu'],
    'tshau': ['ʦʰɑu'],
    'sau': ['sɑu'],
    'kau': ['kɑu'],
    'khau': ['kʰɑu'],
    'gau': ['gɑu'],
    'ngau': ['ŋɑu'],
    'auh': ['ɑuʔ'],
    'hauh': ['hɑuʔ'],
    'pauh': ['pɑuʔ'],
    'phauh': ['pʰɑuʔ'],
    'bauh': ['bɑuʔ'],
    'tauh': ['tɑuʔ'],
    'thauh': ['tʰɑuʔ'],
    'nauh': ['nɑuʔ'],
    'lauh': ['lɑuʔ'],
    'kauh': ['kɑuʔ'],
    'khauh': ['kʰɑuʔ'],
    'ngauh': ['ŋɑuʔ'],
    'e': ['e'],
    'he': ['he'],
    'pe': ['pe'],
    'phe': ['pʰe'],
    'be': ['be'],
    'me': ['me'],
    'te': ['te'],
    'the': ['tʰe'],
    'ne': ['ne'],
    'le': ['le'],
    'tse': ['ʦe'],
    'tshe': ['ʦʰe'],
    'se': ['se'],
    'ke': ['ke'],
    'khe': ['kʰe'],
    'ge': ['ge'],
    'nge': ['ŋe'],
    'enn': ['ẽ'],
    'henn': ['hẽ'],
    'penn': ['pẽ'],
    'phenn': ['pʰẽ'],
    'benn': ['bẽ'],
    'tenn': ['tẽ'],
    'thenn': ['tʰẽ'],
    'tsenn': ['ʦẽ'],
    'tshenn': ['ʦʰẽ'],
    'senn': ['sẽ'],
    'kenn': ['kẽ'],
    'khenn': ['kʰẽ'],
    'geh': ['gẽʔ'],
    'leh': ['lẽʔ'],
    'tsheh': ['ʦʰẽʔ'],
    'si': ['si'],
    'li': ['li'],
    'ki': ['ki'],
    'gok': ['gɔk'],
    'nge': ['ŋe'],
    'enn': ['ẽ'],
    'henn': ['hẽ'],
    'penn': ['pẽ'],
    'phenn': ['pʰẽ'],
    'benn': ['bẽ'],
    'tenn': ['tẽ'],
    'thenn': ['tʰẽ'],
    'tsenn': ['ʦẽ'],
    'tshenn': ['ʦʰẽ'],
    'senn': ['sẽ'],
    'kenn': ['kẽ'],
    'khenn': ['kʰẽ'],
    'eh': ['eʔ'],
    'the': ['tʰe'],
    'ne': ['ne'],
    'le': ['le'],
    'tse': ['ʦe'],
    'tshe': ['ʦʰe'],
    'se': ['se'],
    'ke': ['ke'],
    'khe': ['kʰe'],
    'ge': ['ge'],
    'heh': ['heʔ'],
    'peh': ['peʔ'],
    'pheh': ['pʰeʔ'],
    'beh': ['beʔ'],
    'meh': ['meʔ'],
    'teh': ['teʔ'],
    'theh': ['tʰeʔ'],
    'neh': ['neʔ'],
    'leh': ['leʔ'],
    'tseh': ['ʦeʔ'],
    'tsheh': ['ʦʰeʔ'],
    'seh': ['seʔ'],
    'keh': ['keʔ'],
    'kheh': ['kʰeʔ'],
    'geh': ['geʔ'],
    'ngeh': ['ŋeʔ'],
    'i': ['i'],
    'hi': ['hi'],
    'pi': ['pi'],
    'phi': ['pʰi'],
    'bi': ['bi'],
    'mi': ['mi'],
    'ti': ['ti'],
    'thi': ['tʰi'],
    'ni': ['ni'],
    'li': ['li'],
    'tsi': ['ʦi'],
    'tshi': ['ʦʰi'],
    'ji': ['ʣi'],
    'si': ['si'],
    'ki': ['ki'],
    'khi': ['kʰi'],
    'gi': ['gi'],
    'ngi': ['ŋi'],
    'inn': ['ĩ'],
    'hinn': ['hĩ'],
    'pinn': ['pĩ'],
    'phinn': ['pʰĩ'],
    'binn': ['bĩ'],
    'minn': ['mĩ'],
    'tinn': ['tĩ'],
    'thinn': ['tʰĩ'],
    'tsinn': ['ʦĩ'],
    'tshinn': ['ʦʰĩ'],
    'sinn': ['sĩ'],
    'kinn': ['kĩ'],
    'khinn': ['kʰĩ'],
    'ih': ['iʔ'],
    'pih': ['piʔ'],
    'phih': ['pʰiʔ'],
    'bih': ['biʔ'],
    'mih': ['miʔ'],
    'tih': ['tiʔ'],
    'thih': ['tʰiʔ'],
    'nih': ['niʔ'],
    'lih': ['liʔ'],
    'tsih': ['ʦiʔ'],
    'tshih': ['ʦʰiʔ'],
    'sih': ['siʔ'],
    'kih': ['kiʔ'],
    'khih': ['kʰiʔ'],
    'im': ['im'],
    'him': ['him'],
    'pim': ['pim'],
    'phim': ['pʰim'],
    'bim': ['bim'],
    'mim': ['mim'],
    'tim': ['tim'],
    'thim': ['tʰim'],
    'nim': ['nim'],
    'lim': ['lim'],
    'tsim': ['ʦim'],
    'tshim': ['ʦʰim'],
    'sim': ['sim'],
    'kim': ['kim'],
    'khim': ['kʰim'],
    'gim': ['gim'],
    'in': ['in'],
    'hin': ['hin'],
    'pin': ['pin'],
    'phin': ['pʰin'],
    'bin': ['bin'],
    'min': ['min'],
    'tin': ['tin'],
    'thin': ['tʰin'],
    'nin': ['nin'],
    'lin': ['lin'],
    'tsin': ['ʦin'],
    'tshin': ['ʦʰin'],
    'jin': ['ʣin'],
    'sin': ['sin'],
    'kin': ['kin'],
    'khin': ['kʰin'],
    'gin': ['gin'],
    'ing': ['iŋ'],
    'hing': ['hiŋ'],
    'ping': ['piŋ'],
    'phing': ['pʰiŋ'],
    'bing': ['biŋ'],
    'ming': ['miŋ'],
    'ting': ['tiŋ'],
    'thing': ['tʰiŋ'],
    'ning': ['niŋ'],
    'ling': ['liŋ'],
    'tsing': ['ʦiŋ'],
    'tshing': ['ʦʰiŋ'],
    'sing': ['siŋ'],
    'king': ['kiŋ'],
    'khing': ['kʰiŋ'],
    'ging': ['giŋ'],
    'ip': ['ip̚'],
    'hip': ['hip̚'],
    'pip': ['pip̚'],
    'phip': ['pʰip̚'],
    'bip': ['bip̚'],
    'mip': ['mip̚'],
    'tip': ['tip̚'],
    'thip': ['tʰip̚'],
    'nip': ['nip̚'],
    'lip': ['lip̚'],
    'tsip': ['ʦip̚'],
    'tship': ['ʦʰip̚'],
    'sip': ['sip̚'],
    'kip': ['kip̚'],
    'khip': ['kʰip̚'],
    'it': ['it̚'],
    'hit': ['hit̚'],
    'pit': ['pit̚'],
    'phit': ['pʰit̚'],
    'bit': ['bit̚'],
    'mit': ['mit̚'],
    'tit': ['tit̚'],
    'thit': ['tʰit̚'],
    'lit': ['lit̚'],
    'tsit': ['ʦit̚'],
    'tshit': ['ʦʰit̚'],
    'sit': ['sit̚'],
    'kit': ['kit̚'],
    'khit': ['kʰit̚'],
    'ik': ['ik̚'],
    'hik': ['hik̚'],
    'pik': ['pik̚'],
    'phik': ['pʰik̚'],
    'bik': ['bik̚'],
    'mik': ['mik̚'],
    'tik': ['tik̚'],
    'thik': ['tʰik̚'],
    'lik': ['lik̚'],
    'tsik': ['ʦik̚'],
    'tshik': ['ʦʰik̚'],
    'jik': ['ʣik̚'],
    'sik': ['sik̚'],
    'kik': ['kik̚'],
    'khik': ['kʰik̚'],
    'gik': ['gik̚'],
    'ia': ['iɑ'],
    'hia': ['hiɑ'],
    'pia': ['piɑ'],
    'phia': ['pʰiɑ'],
    'bia': ['biɑ'],
    'mia': ['miɑ'],
    'tia': ['tiɑ'],
    'thia': ['tʰiɑ'],
    'nia': ['niɑ'],
    'lia': ['liɑ'],
    'tsia': ['ʦiɑ'],
    'tshia': ['ʦʰiɑ'],
    'jia': ['ʣiɑ'],
    'sia': ['siɑ'],
    'kia': ['kiɑ'],
    'khia': ['kʰiɑ'],
    'gia': ['giɑ'],
    'ngia': ['ŋiɑ'],
    'iann': ['iɑ̃'],
    'hiann': ['hiɑ̃'],
    'piann': ['piɑ̃'],
    'phiann': ['pʰiɑ̃'],
    'biann': ['biɑ̃'],
    'miann': ['miɑ̃'],
    'tiann': ['tiɑ̃'],
    'thiann': ['tʰiɑ̃'],
    'niann': ['niɑ̃'],
    'liann': ['liɑ̃'],
    'tsiann': ['ʦiɑ̃'],
    'tshiann': ['ʦʰiɑ̃'],
    'jiann': ['ʣiɑ̃'],
    'siann': ['siɑ̃'],
    'kiann': ['kiɑ̃'],
    'khiann': ['kʰiɑ̃'],
    'giann': ['giɑ̃'],
    'ngiann': ['ŋiɑ̃'],
    'iah': ['iɑʔ'],
    'hiah': ['hiɑʔ'],
    'piah': ['piɑʔ'],
    'phiah': ['pʰiɑʔ'],
    'biah': ['biɑʔ'],
    'miah': ['miɑʔ'],
    'tiah': ['tiɑʔ'],
    'thiah': ['tʰiɑʔ'],
    'liah': ['liɑʔ'],
    'tsiah': ['ʦiɑʔ'],
    'tshiah': ['ʦʰiɑʔ'],
    'siah': ['siɑʔ'],
    'kiah': ['kiɑʔ'],
    'khiah': ['kʰiɑʔ'],
        'giah': ['giɑʔ'],
    'ngiah': ['ŋiɑʔ'],
    'iam': ['iɑm'],
    'hiam': ['hiɑm'],
    'piam': ['piɑm'],
    'phiam': ['pʰiɑm'],
    'miam': ['miɑm'],
    'tiam': ['tiɑm'],
    'thiam': ['tʰiɑm'],
    'liam': ['liɑm'],
    'tsiam': ['ʦiɑm'],
    'tshiam': ['ʦʰiɑm'],
    'jiam': ['ʣiɑm'],
    'siam': ['siɑm'],
    'kiam': ['kiɑm'],
    'khiam': ['kʰiɑm'],
    'giam': ['giɑm'],
    'ian': ['iɑn'],
    'hian': ['hiɑn'],
    'pian': ['piɑn'],
    'phian': ['pʰiɑn'],
    'bian': ['biɑn'],
    'mian': ['miɑn'],
    'tian': ['tiɑn'],
    'thian': ['tʰiɑn'],
    'nian': ['niɑn'],
    'lian': ['liɑn'],
    'tsian': ['ʦiɑn'],
    'tshian': ['ʦʰiɑn'],
    'jian': ['ʣiɑn'],
    'sian': ['siɑn'],
    'kian': ['kiɑn'],
    'khian': ['kʰiɑn'],
    'gian': ['giɑn'],
    'iang': ['iɑŋ'],
    'hiang': ['hiɑŋ'],
    'piang': ['piɑŋ'],
    'phiang': ['pʰiɑŋ'],
    'biang': ['biɑŋ'],
    'tiang': ['tiɑŋ'],
    'thang': ['tʰiɑŋ'],
    'liang': ['liɑŋ'],
    'tsiang': ['ʦiɑŋ'],
    'tshang': ['ʦʰiɑŋ'],
    'jiang': ['ʣiɑŋ'],
    'siang': ['siɑŋ'],
    'kiang': ['kiɑŋ'],
    'khiang': ['kʰiɑŋ'],
    'giang': ['giɑŋ'],
    'iap': ['iɑp̚'],
    'hiap': ['hiɑp̚'],
    'piap': ['piɑp̚'],
    'phiap': ['pʰiɑp̚'],
    'liap': ['liɑp̚'],
    'tsiap': ['ʦiɑp̚'],
    'tshiap': ['ʦʰiɑp̚'],
    'jiap': ['ʣiɑp̚'],
    'siap': ['siɑp̚'],
    'kiap': ['kiɑp̚'],
    'khiap': ['kʰiɑp̚'],
    'giap': ['giɑp̚'],
    'iat': ['iɑt̚'],
    'hiat': ['hiɑt̚'],
    'piat': ['piɑt̚'],
    'phiat': ['pʰiɑt̚'],
    'biat': ['biɑt̚'],
    'tiat': ['tiɑt̚'],
    'thiat': ['tʰiɑt̚'],
    'liat': ['liɑt̚'],
    'tsiat': ['ʦiɑt̚'],
    'tshiat': ['ʦʰiɑt̚'],
    'jiat': ['ʣiɑt̚'],
    'siat': ['siɑt̚'],
    'kiat': ['kiɑt̚'],
    'khiat': ['kʰiɑt̚'],
    'giat': ['giɑt̚'],
    'iak': ['iɑk̚'],
    'hiak': ['hiɑk̚'],
    'piak': ['piɑk̚'],
    'phiak': ['pʰiɑk̚'],
    'tiak': ['tiɑk̚'],
    'thak': ['tʰiɑk̚'],
    'tshak': ['ʦʰiɑk̚'],
    'kiak': ['kiɑk̚'],
    'khak': ['kʰiɑk̚'],
    'iak': ['iɑk̚'],
    'iau': ['iɑu'],
    'hiau': ['hiɑu'],
    'piau': ['piɑu'],
    'phiau': ['pʰiɑu'],
    'biau': ['biɑu'],
    'miau': ['miɑu'],
    'tiau': ['tiɑu'],
    'thiau': ['tʰiɑu'],
    'niau': ['niɑu'],
    'liau': ['liɑu'],
    'tsiau': ['ʦiɑu'],
    'tshiau': ['ʦʰiɑu'],
    'jiau': ['ʣiɑu'],
    'siau': ['siɑu'],
    'kiau': ['kiɑu'],
    'khiau': ['kʰiɑu'],
    'giau': ['giɑu'],
    'ngiau': ['ŋiɑu'],
    'iauh': ['iɑuʔ'],
    'hiauh': ['hiɑuʔ'],
    'phiauh': ['pʰiɑuʔ'],
    'tshiauh': ['ʦʰiɑuʔ'],
    'kiah': ['kiɑʔ'],
    'ngiauh': ['ŋiɑuʔ'],
    'io': ['io'],
    'hio': ['hio'],
    'pio': ['pio'],
    'phio': ['pʰio'],
    'bio': ['bio'],
    'tio': ['tio'],
    'thio': ['tʰio'],
    'lio': ['lio'],
    'tsio': ['ʦio'],
    'tshio': ['ʦʰio'],
    'jio': ['ʣio'],
    'sio': ['sio'],
    'kio': ['kio'],
    'khio': ['kʰio'],
    'gio': ['gio'],
    'ionn': ['iɔ̃'],
    'hionn': ['hiɔ̃'],
    'pionn': ['piɔ̃'],
    'phionn': ['pʰiɔ̃'],
    'tiann': ['tiɔ̃'],
    'tsionn': ['ʦiɔ̃'],
    'sionn': ['siɔ̃'],
    'kionn': ['kiɔ̃'],
    'khoann': ['kʰiɔ̃'],
    'ioh': ['ioʔ'],
    'hioh': ['hioʔ'],
    'tioh': ['tioʔ'],
    'lioh': ['lioʔ'],
    'tsioh': ['ʦioʔ'],
    'gioh': ['gioʔ'],
    'iong': ['ioŋ'],
    'hiong': ['hioŋ'],
    'tiong': ['tioŋ'],
    'thiong': ['tʰioŋ'],
    'liongo': ['lioŋ'],
    'tsiong': ['ʦioŋ'],
    'tshiong': ['ʦʰioŋ'],
    'siong': ['sioŋ'],
    'kiong': ['kioŋ'],
    'khiong': ['kʰioŋ'],
    'giang': ['giɑŋ'],
    'u': ['u'],
    'hu': ['hu'],
    'pu': ['pu'],
    'phu': ['pʰu'],
    'bu': ['bu'],
    'mu': ['mu'],
    'tu': ['tu'],
    'thu': ['tʰu'],
    'lu': ['lu'],
    'tsu': ['ʦu'],
    'tshu': ['ʦʰu'],
    'ju': ['ʣu'],
    'su': ['su'],
    'ku': ['ku'],
    'khu': ['kʰu'],
    'gu': ['gu'],
    'uh': ['uʔ'],
    'huh': ['huʔ'],
    'puh': ['puʔ'],
    'phuh': ['pʰuʔ'],
    'buh': ['buʔ'],
    'tuh': ['tuʔ'],
    'thuh': ['tʰuʔ'],
    'luh': ['luʔ'],
    'tsuh': ['ʦuʔ'],
    'tshuh': ['ʦʰuʔ'],
    'suh': ['suʔ'],
    'kun': ['kuʔ'],
    'ui': ['ui'],
    'hui': ['hui'],
    'pui': ['pui'],
    'phui': ['pʰui'],
    'bui': ['bui'],
    'mui': ['mui'],
       'tui': ['tui'],
    'thui': ['tʰui'],
    'nui': ['nui'],
    'lui': ['lui'],
    'tsui': ['ʦui'],
    'tshui': ['ʦʰui'],
    'sui': ['sui'],
    'kui': ['kui'],
    'khui': ['kʰui'],
    'gui': ['gui'],
    'ngui': ['ŋui'],
    'uih': ['uiʔ'],
    'huih': ['huiʔ'],
    'puih': ['puiʔ'],
    'phuih': ['pʰuiʔ'],
    'buih': ['buiʔ'],
    'muih': ['muiʔ'],
    'tuih': ['tuiʔ'],
    'thuih': ['tʰuiʔ'],
    'luih': ['luiʔ'],
    'tsuih': ['ʦuiʔ'],
    'tshuih': ['ʦʰuiʔ'],
    'suih': ['suiʔ'],
    'kuih': ['kuiʔ'],
    'khuih': ['kʰuiʔ'],
    'guih': ['guiʔ'],
    'un': ['un'],
    'hun': ['hun'],
    'pun': ['pun'],
    'phun': ['pʰun'],
    'bun': ['bun'],
    'mun': ['mun'],
    'tun': ['tun'],
    'thun': ['tʰun'],
    'nun': ['nun'],
    'lun': ['lun'],
    'tsun': ['ʦun'],
    'tshun': ['ʦʰun'],
    'sun': ['sun'],
    'kun': ['kun'],
    'khun': ['kʰun'],
    'gun': ['gun'],
    'ngun': ['ŋun'],
    'ut': ['ut̚'],
    'hut': ['hut̚'],
    'put': ['put̚'],
    'phut': ['pʰut̚'],
    'but': ['but̚'],
    'mut': ['mut̚'],
    'tut': ['tut̚'],
    'thut': ['tʰut̚'],
    'lut': ['lut̚'],
    'tsut': ['ʦut̚'],
    'tshut': ['ʦʰut̚'],
    'sut': ['sut̚'],
    'kut': ['kut̚'],
    'khut': ['kʰut̚'],
    'gut': ['gut̚'],
    'ua': ['uɑ'],
    'hua': ['huɑ'],
    'pua': ['puɑ'],
    'phua': ['pʰuɑ'],
    'bua': ['buɑ'],
    'mua': ['muɑ'],
    'tua': ['tuɑ'],
    'thua': ['tʰuɑ'],
    'nua': ['nuɑ'],
    'lua': ['luɑ'],
    'tsua': ['ʦuɑ'],
    'tshua': ['ʦʰuɑ'],
    'jua': ['ʣuɑ'],
    'sua': ['suɑ'],
    'kua': ['kuɑ'],
    'khua': ['kʰuɑ'],
    'gua': ['guɑ'],
    'ngua': ['ŋuɑ'],
    'uann': ['uɑ̃'],
    'huann': ['huɑ̃'],
    'puann': ['puɑ̃'],
    'phuann': ['pʰuɑ̃'],
    'tuann': ['tuɑ̃'],
    'thuann': ['tʰuɑ̃'],
    'tsuann': ['ʦuɑ̃'],
    'tshuann': ['ʦʰuɑ̃'],
    'suann': ['suɑ̃'],
    'kuann': ['kuɑ̃'],
    'khua': ['kʰuɑ̃'],
    'uah': ['uɑʔ'],
    'huah': ['huɑʔ'],
    'puah': ['puɑʔ'],
    'phuah': ['pʰuɑʔ'],
    'buah': ['buɑʔ'],
    'tuah': ['tuɑʔ'],
    'thuah': ['tʰuɑʔ'],
    'luah': ['luɑʔ'],
    'tsuah': ['ʦuɑʔ'],
    'tshuah': ['ʦʰuɑʔ'],
    'suah': ['suɑʔ'],
    'kuah': ['kuɑʔ'],
    'khua': ['kʰuɑʔ'],
    'uan': ['uɑn'],
    'huan': ['huɑn'],
    'puan': ['puɑn'],
    'phuan': ['pʰuɑn'],
    'buan': ['buɑn'],
    'tuan': ['tuɑn'],
    'thuan': ['tʰuɑn'],
    'luan': ['luɑn'],
    'tsuan': ['ʦuɑn'],
    'tshuan': ['ʦʰuɑn'],
    'suan': ['suɑn'],
    'kuan': ['kuɑn'],
    'khuan': ['kʰuɑn'],
    'guan': ['guɑn'],
    'uang': ['uɑŋ'],
    'huang': ['huɑŋ'],
    'tsuang': ['ʦuɑŋ'],
    'tshuang': ['ʦʰuɑŋ'],
    'uang': ['uɑŋ'],
    'uat': ['uɑt̚'],
    'huat': ['huɑt̚'],
    'puat': ['puɑt̚'],
    'phuat': ['pʰuɑt̚'],
    'buat': ['buɑt̚'],
    'tuat': ['tuɑt̚'],
    'thuat': ['tʰuɑt̚'],
    'luat': ['luɑt̚'],
    'tsuat': ['ʦuɑt̚'],
    'tshuat': ['ʦʰuɑt̚'],
    'suat': ['suɑt̚'],
    'kuat': ['kuɑt̚'],
    'khuat': ['kʰuɑt̚'],
    'guat': ['guɑt̚'],
    'uai': ['uɑi'],
    'huai': ['huɑi'],
    'tsuai': ['ʦuɑi'],
    'suai': ['suɑi'],
    'kuai': ['kuɑi'],
    'khua': ['kʰuɑi'],
    'ue': ['ue'],
    'hue': ['hue'],
    'pue': ['pue'],
    'phue': ['pʰue'],
    'bue': ['bue'],
    'mue': ['mue'],
    'tue': ['tue'],
    'thue': ['tʰue'],
    'lue': ['lue'],
    'tsue': ['ʦue'],
    'tshue': ['ʦʰue'],
    'jue': ['ʣue'],
    'sue': ['sue'],
    'kue': ['kue'],
    'khue': ['kʰue'],
    'gue': ['gue'],
    'ueh': ['ueʔ'],
    'hueh': ['hueʔ'],
    'pueh': ['pueʔ'],
    'phueh': ['pʰueʔ'],
    'bueh': ['bueʔ'],
    'mueh': ['mueʔ'],
    'thueh': ['tʰueʔ'],
    'lueh': ['lueʔ'],
    'tsueh': ['ʦueʔ'],
    'tshueh': ['ʦʰueʔ'],
    'sueh': ['sueʔ'],
    'kueh': ['kueʔ'],
    'khueh': ['kʰueʔ'],
    'gueh': ['gueʔ'],
    'ui': ['ui'],
    'hui': ['hui'],
    'pui': ['pui'],
    'phui': ['pʰui'],
    'bui': ['bui'],
    'mui': ['mui'],
    'tui': ['tui'],
    'thui': ['tʰui'],
    'lui': ['lui'],
    'tsui': ['ʦui'],
    'tshui': ['ʦʰui'],
    'sui': ['sui'],
    'kui': ['kui'],
    'khui': ['kʰui'],
    'gui': ['gui'],
    'uinn': ['uĩ'],
    'huinn': ['huĩ'],
    'puinn': ['puĩ'],
    'phuinn': ['pʰuĩ'],
    'tsuinn': ['ʦuĩ'],
    'tshuinn': ['ʦʰuĩ'],
    'suinn': ['suĩ'],
    'kuinn': ['kuĩ'],
    'khuinn': ['kʰuĩ'],
    'guih': ['guiʔ'],
    'm': ['m̩'],
    'hm': ['hm̩'],
    'mh': ['m̩ʔ'],
    'hmh': ['hm̩ʔ'],
    'ng': ['ŋ̍'],
    'hng': ['hŋ̍'],
    'png': ['pŋ̍'],
    'mng': ['mŋ̍'],
    'tng': ['tŋ̍'],
    'thng': ['tʰŋ̍'],
    'nng': ['nŋ̍'],
    'tsng': ['ʦŋ̍'],
    'tshng': ['ʦʰŋ̍'],
    'sng': ['sŋ̍'],
    'kng': ['kŋ̍'],
    'khng': ['kʰŋ̍'],
    'ngh': ['ŋ̍ʔ'],
    'hngh': ['hŋ̍ʔ'],
    'mngh': ['mŋ̍ʔ'],
    'tsngh': ['ʦŋ̍ʔ'],
    'tshngh': ['ʦʰŋ̍ʔ'],
    'sngh': ['sŋ̍ʔ'],
    'kngh': ['kŋ̍ʔ'],
    'khngh': ['kʰŋ̍ʔ'],
   
    # ユーザーが提示したエントリ
    'ngoo': ['ŋɔ'],
    'honn': ['hɔ̃'],
}
