PINYIN_DICT = {
    "a": ["ɑ"],
    "iann": ["iã"],
     "b": ["b"],
    "e": ["e"],
    "ee": ["ɛ"],
    #自動的に追加したもの
"--ann": ['ã'],
"ann": ['ã'],
"ah": ['aʔ'],
"--ai": ['ai'],
"ai": ['ai'],
"--ainn": ['aĩ'],
"ainn": ['aĩ'],
"--iau": ['ɪaʊ'],
"iau": ['ɪaʊ'],
"--jainn": ['dzaĩ'],
"jainn": ['dzaĩ'],
"--jiai": ['ʑai'],
"jiai": ['ʑai'],
"--jiau": ['ʑɪaʊ'],
"jiau": ['ʑɪaʊ'],
"ak": ['ak'],
"--am": ['am'],
"am": ['am'],
"ap": ['ap'],
"--siau": ['ɕɪaʊ'],
"siau": ['ɕɪaʊ'],
"at": ['at'],
"--au": ['au'],
"au": ['au'],
"--ba": ['ba'],
"ba": ['ba'],
"--bann": ['bã'],
"bann": ['bã'],
"bah": ['baʔ'],
"--biau": ['bɪaʊ'],
"biau": ['bɪaʊ'],
"--bai": ['bai'],
"bai": ['bai'],
"--bainn": ['baĩ'],
"bainn": ['baĩ'],
"bak": ['bak'],
"--bam": ['bam'],
"bam": ['bam'],
"bap": ['bap'],
"bat": ['bat'],
"--bau": ['bau'],
"bau": ['bau'],
"--bir": ['bɨ'],
"bir": ['bɨ'],
"--be": ['be'],
"be": ['be'],
"--benn": ['bẽ'],
"benn": ['bẽ'],
"--bio": ['bɪə'],
"bio": ['bɪə'],
"--bo": ['bo'],
"bo": ['bo'],
"--bian": ['bɪɛn'],
"bian": ['bɪɛn'],
"--bi": ['bi'],
"bi": ['bi'],
"--binn": ['bĩ'],
"binn": ['bĩ'],
"--bim": ['bim'],
"bim": ['bim'],
"--bin": ['bin'],
"bin": ['bin'],
"--bing": ['biŋ'],
"bing": ['biŋ'],
"bit": ['bit'],
"--biu": ['biu'],
"biu": ['biu'],
"--biunn": ['biũ'],
"biunn": ['biũ'],
"bik": ['bɪk'],
"--boo": ['bɔ'],
"boo": ['bɔ'],
"--bonn": ['bɔ̃'],
"bonn": ['bɔ̃'],
"bok": ['bɔk'],
"--bong": ['bɔŋ'],
"bong": ['bɔŋ'],
"--bua": ['bua'],
"bua": ['bua'],
"--buai": ['buai'],
"buai": ['buai'],
"--buan": ['buan'],
"buan": ['buan'],
"--bu": ['bu'],
"bu": ['bu'],
"--bue": ['bue'],
"bue": ['bue'],
"--jai": ['dzai'],
"jai": ['dzai'],
"jah": ['dzaʔ'],
"--ja": ['dza'],
"ja": ['dza'],
"--jann": ['dzã'],
"jann": ['dzã'],
"jak": ['dzak'],
"--jam": ['dzam'],
"jam": ['dzam'],
"jap": ['dzap'],
"jat": ['dzat'],
"--jau": ['dzau'],
"jau": ['dzau'],
"--je": ['dze'],
"je": ['dze'],
"--jenn": ['dzẽ'],
"jenn": ['dzẽ'],
"--jo": ['dzo'],
"jo": ['dzo'],
"--jng": ['dzŋ̍'],
"jng": ['dzŋ̍'],
"--joo": ['dzɔ'],
"joo": ['dzɔ'],
"--jonn": ['dzɔ̃'],
"jonn": ['dzɔ̃'],
"jok": ['dzɔk'],
"--jong": ['dzɔŋ'],
"jong": ['dzɔŋ'],
"--juai": ['dzuai'],
"juai": ['dzuai'],
"--jua": ['dzua'],
"jua": ['dzua'],
"--juan": ['dzuan'],
"juan": ['dzuan'],
"--jue": ['ʑue'],
"jue": ['ʑue'],
"--ju": ['dzu'],
"ju": ['dzu'],
"--e": ['e'],
"e": ['e'],
"--enn": ['ẽ'],
"enn": ['ẽ'],
"ioh": ['ɪəʔ'],
"--io": ['ɪə'],
"io": ['ɪə'],
"--jio": ['ʑio'],
"jio": ['ʑiu'],
"--ian": ['ɪɛn'],
"ian": ['ɪɛn'],
"--jian": ['ʑɪɛn'],
"jian": ['ʑɪɛn'],
"--sian": ['sɪɛn'],
"sian": ['sɪɛn'],
"--o": ['o'],
"o": ['o'],
"--sio": ['ɕio'],
"sio": ['ɕio'],
"--ga": ['ga'],
"ga": ['ga'],
"--gann": ['gã'],
"gann": ['gã'],
"gah": ['gaʔ'],
"--giau": ['gɪaʊ'],
"giau": ['gɪaʊ'],
"--gai": ['gai'],
"gai": ['gai'],
"--gainn": ['gaĩ'],
"gainn": ['gaĩ'],
"gak": ['gak'],
"--gam": ['gam'],
"gam": ['gam'],
"gap": ['gap'],
"gat": ['gat'],
"--gau": ['gau'],
"gau": ['gau'],
"--ge": ['ge'],
"ge": ['ge'],
"--genn": ['gẽ'],
"genn": ['gẽ'],
"--gio": ['gɪə'],
"gio": ['giu'],
"gioh": ['gɪəʔ'],
"--go": ['go'],
"go": ['go'],
"--gian": ['gɪɛn'],
"gian": ['gɪɛn'],
"--gir": ['gɨ'],
"gir": ['gɨ'],
"--gi": ['gi'],
"gi": ['gi'],
"--ginn": ['gĩ'],
"ginn": ['gĩ'],
"--gim": ['gim'],
"gim": ['gim'],
"--ging": ['giŋ'],
"ging": ['giŋ'],
"--gin": ['gin'],
"gin": ['gin'],
"--giu": ['giu'],
"giu": ['giu'],
"--giunn": ['giũ'],
"giunn": ['giũ'],
"gik": ['gɪk'],
"--gng": ['gŋ̍'],
"gng": ['gŋ̍'],
"--goo": ['gɔ'],
"goo": ['gɔ'],
"--gonn": ['gɔ̃'],
"gonn": ['gɔ̃'],
"giok": ['gɪɔk'],
"gok": ['gɔk'],
"--giong": ['gɪɔŋ'],
"giong": ['gɪɔŋ'],
"--gong": ['gɔŋ'],
"gong": ['gɔŋ'],
"--gua": ['gua'],
"gua": ['gua'],
"--guai": ['guai'],
"guai": ['guai'],
"--guan": ['guan'],
"guan": ['guan'],
"--gue": ['gue'],
"gue": ['gue'],
"--gu": ['gu'],
"gu": ['gu'],
"--ha": ['ha'],
"ha": ['ha'],
"--hann": ['hã'],
"hann": ['hã'],
"hah": ['haʔ'],
"--hiau": ['hɪaʊ'],
"hiau": ['hɪaʊ'],
"--hai": ['hai'],
"hai": ['hai'],
"--hainn": ['haĩ'],
"hainn": ['haĩ'],
"hak": ['hak'],
"--ham": ['ham'],
"ham": ['ham'],
"hap": ['hap'],
"hat": ['hat'],
"--hau": ['hau'],
"hau": ['hau'],
"--he": ['he'],
"he": ['he'],
"--henn": ['hẽ'],
"henn": ['hẽ'],
"hioh": ['hɪəʔ'],
"--hio": ['hɪə'],
"hio": ['hiu'],
"--ho": ['ho'],
"ho": ['ho'],
"--hian": ['hɪɛn'],
"hian": ['hɪɛn'],
"--hir": ['hɨ'],
"hir": ['hɨ'],
"--hi": ['hi'],
"hi": ['hi'],
"--hinn": ['hĩ'],
"hinn": ['hĩ'],
"--him": ['him'],
"him": ['him'],
"--hing": ['hiŋ'],
"hing": ['hiŋ'],
"--hin": ['hin'],
"hin": ['hin'],
"hip": ['hip'],
"hit": ['hit'],
"--hiu": ['hiu'],
"hiu": ['hiu'],
"--hiunn": ['hiũ'],
"hiunn": ['hiũ'],
"hik": ['hɪk'],
"--hng": ['hŋ̍'],
"hng": ['hŋ̍'],
"--hoo": ['hɔ'],
"hoo": ['hɔ'],
"--honn": ['hɔ̃'],
"honn": ['hɔ̃'],
"hiok": ['hɪɔk'],
"hok": ['hɔk'],
"--hiong": ['hɪɔŋ'],
"hiong": ['hɪɔŋ'],
"--hong": ['hɔŋ'],
"hong": ['hɔŋ'],
"--hua": ['hua'],
"hua": ['hua'],
"--huai": ['huai'],
"huai": ['huai'],
"--huan": ['huan'],
"huan": ['huan'],
"--hue": ['hue'],
"hue": ['hue'],
"--hu": ['hu'],
"hu": ['hu'],
"--siai": ['ɕiai'],
"siai": ['ɕiai'],
"--siainn": ['ɕiaĩ'],
"siainn": ['ɕiaĩ'],
"jiah": ['ʑiaʔ'],
"--jia": ['ʑia'],
"jia": ['ʑia'],
"--jiann": ['ʑiã'],
"jiann": ['ʑiã'],
"jiak": ['ʑiak'],
"siak": ['ɕiak'],
"--jiam": ['ʑiam'],
"jiam": ['ʑiam'],
"--siam": ['ɕiam'],
"siam": ['ɕiam'],
"jiap": ['ʑiap'],
"siap": ['ɕiap'],
"siah": ['ɕiaʔ'],
"--sia": ['ɕia'],
"sia": ['ɕia'],
"--siann": ['ɕiã'],
"siann": ['ɕiã'],
"jiat": ['ʑiat'],
"siat": ['ɕiat'],
"--jie": ['ʑie'],
"jie": ['ʑie'],
"--jienn": ['ʑiẽ'],
"jienn": ['ʑiẽ'],
"--sie": ['ɕie'],
"sie": ['ɕie'],
"--sienn": ['ɕiẽ'],
"sienn": ['ɕiẽ'],
"--i": ['i'],
"i": ['i'],
"--inn": ['ĩ'],
"inn": ['ĩ'],
"--ir": ['ɨ'],
"ir": ['ɨ'],
"--sinn": ['sĩ'],
"sinn": ['sĩ'],
"--siiunn": ['ɕiiũ'],
"siiunn": ['ɕiiũ'],
"--ji": ['ʑi'],
"ji": ['ʑi'],
"--im": ['im'],
"im": ['im'],
"--jim": ['ʑim'],
"jim": ['ʑim'],
"--sim": ['sim'],
"sim": ['sim'],
"--ing": ['iŋ'],
"ing": ['iŋ'],
"--jing": ['ʑiŋ̍'],
"jing": ['ʑiŋ̍'],
"--sing": ['siŋ'],
"sing": ['siŋ'],
"--in": ['in'],
"in": ['in'],
"--jin": ['ʑin'],
"jin": ['ʑin'],
"--sin": ['ɕin'],
"sin": ['ɕin'],
"--jioo": ['ʑiɔ'],
"jioo": ['ʑiɔ'],
"--jionn": ['ʑiɔ̃'],
"jionn": ['ʑiɔ̃'],
"jiok": ['ʑiɔk'],
"--sioo": ['ɕiɔ'],
"sioo": ['ɕiɔ'],
"--sionn": ['ɕiɔ̃'],
"sionn": ['ɕiɔ̃'],
"ip": ['ip'],
"jip": ['ʑip'],
"--si": ['si'],
"si": ['si'],
"--sir": ['sɨ'],
"sir": ['sɨ'],
"it": ['it'],
"jit": ['ʑit'],
"--siuan": ['ɕiuan'],
"siuan": ['ɕiuan'],
"--siua": ['ɕiua'],
"siua": ['ɕiua'],
"--siue": ['ɕiue'],
"siue": ['ɕiue'],
"--iu": ['iu'],
"iu": ['iu'],
"--iunn": ['iũ'],
"iunn": ['iũ'],
"--jiu": ['ʑiu'],
"jiu": ['ʑiu'],
"--siu": ['ɕiu'],
"siu": ['ɕiu'],
"--jir": ['ʑɨ'],
"jir": ['ʑɨ'],
"--kai": ['kai'],
"kai": ['kai'],
"--kainn": ['kaĩ'],
"kainn": ['kaĩ'],
"--khai": ['kʰai'],
"khai": ['kʰai'],
"--khainn": ['kʰaĩ'],
"khainn": ['kʰaĩ'],
"kah": ['kaʔ'],
"--ka": ['ka'],
"ka": ['ka'],
"--kann": ['kã'],
"kann": ['kã'],
"khah": ['kʰaʔ'],
"--kha": ['kʰa'],
"kha": ['kʰa'],
"--khann": ['kʰã'],
"khann": ['kʰã'],
"--khiau": ['kʰɪaʊ'],
"khiau": ['kʰɪaʊ'],
"--kiau": ['kɪaʊ'],
"kiau": ['kɪaʊ'],
"kak": ['kak'],
"khak": ['kʰak'],
"--kam": ['kam'],
"kam": ['kam'],
"--kham": ['kʰam'],
"kham": ['kʰam'],
"kap": ['kap'],
"khap": ['kʰap'],
"kat": ['kat'],
"khat": ['kʰat'],
"--kau": ['kau'],
"kau": ['kau'],
"--khau": ['kʰau'],
"khau": ['kʰau'],
"--ke": ['ke'],
"ke": ['ke'],
"--kenn": ['kẽ'],
"kenn": ['kẽ'],
"--khe": ['kʰe'],
"khe": ['kʰe'],
"--khenn": ['kʰẽ'],
"khenn": ['kʰẽ'],
"khioh": ['kʰɪəʔ'],
"--khio": ['kʰɪə'],
"khio": ['kʰiu'],
"--kho": ['kʰo'],
"kho": ['kʰo'],
"ik": ['ɪk'],
"kioh": ['kɪəʔ'],
"--kio": ['kɪə'],
"kio": ['kiu'],
"--ko": ['ko'],
"ko": ['ko'],
"--khian": ['kʰɪɛn'],
"khian": ['kʰɪɛn'],
"--kian": ['kɪɛn'],
"kian": ['kɪɛn'],
"--khi": ['kʰi'],
"khi": ['kʰi'],
"--khinn": ['kʰĩ'],
"khinn": ['kʰĩ'],
"--ki": ['ki'],
"ki": ['ki'],
"--kinn": ['kĩ'],
"kinn": ['kĩ'],
"--khim": ['kʰim'],
"khim": ['kʰim'],
"--kim": ['kim'],
"kim": ['kim'],
"--king": ['kiŋ'],
"king": ['kiŋ'],
"--khing": ['kʰiŋ'],
"khing": ['kʰiŋ'],
"--khin": ['kʰin'],
"khin": ['kʰin'],
"--kin": ['kin'],
"kin": ['kin'],
"khip": ['kʰip'],
"kip": ['kip'],
"khit": ['kʰit'],
"kit": ['kit'],
"--khiu": ['kʰiu'],
"khiu": ['kʰiu'],
"--khiunn": ['kʰiũ'],
"khiunn": ['kʰiũ'],
"--kiu": ['kiu'],
"kiu": ['kiu'],
"--kiunn": ['kiũ'],
"kiunn": ['kiũ'],
"jik": ['ʑɪk'],
"--khir": ['kʰɨ'],
"khir": ['kʰɨ'],
"--kir": ['kɨ'],
"kir": ['kɨ'],
"kik": ['kɪk'],
"khik": ['kʰɪk'],
"--khng": ['kʰŋ̍'],
"khng": ['kʰŋ̍'],
"--kng": ['kŋ̍'],
"kng": ['kŋ̍'],
"--khoo": ['kʰɔ'],
"khoo": ['kʰɔ'],
"--khonn": ['kʰɔ̃'],
"khonn": ['kʰɔ̃'],
"khiok": ['kʰɪɔk'],
"khok": ['kʰɔk'],
"kiok": ['kɪɔk'],
"kok": ['kɔk'],
"--koo": ['kɔ'],
"koo": ['kɔ'],
"--konn": ['kɔ̃'],
"konn": ['kɔ̃'],
"--khiong": ['kʰɪɔŋ'],
"khiong": ['kʰɪɔŋ'],
"--khong": ['kʰɔŋ'],
"khong": ['kʰɔŋ'],
"--kiong": ['kɪɔŋ'],
"kiong": ['kɪɔŋ'],
"--kong": ['kɔŋ'],
"kong": ['kɔŋ'],
"sik": ['sɪk'],
"--khuai": ['kʰuai'],
"khuai": ['kʰuai'],
"--kuai": ['kuai'],
"kuai": ['kuai'],
"--khua": ['kʰua'],
"khua": ['kʰua'],
"--kua": ['kua'],
"kua": ['kua'],
"--khuan": ['kʰuan'],
"khuan": ['kʰuan'],
"--kuan": ['kuan'],
"kuan": ['kuan'],
"--khue": ['kʰue'],
"khue": ['kʰue'],
"--kue": ['kue'],
"kue": ['kue'],
"--khu": ['kʰu'],
"khu": ['kʰu'],
"--ku": ['ku'],
"ku": ['ku'],
"--lai": ['lai'],
"lai": ['lai'],
"--lainn": ['laĩ'],
"lainn": ['laĩ'],
"lak": ['lak'],
"lah": ['laʔ'],
"--la": ['la'],
"la": ['la'],
"--lann": ['lã'],
"lann": ['lã'],
"--liau": ['lɪaʊ'],
"liau": ['lɪaʊ'],
"--lam": ['lam'],
"lam": ['lam'],
"lap": ['lap'],
"lat": ['lat'],
"--lau": ['lau'],
"lau": ['lau'],
"--le": ['le'],
"le": ['le'],
"--lenn": ['lẽ'],
"lenn": ['lẽ'],
"lioh": ['lɪəʔ'],
"--lio": ['lɪə'],
"lio": ['liu'],
"--lo": ['lo'],
"lo": ['lo'],
"--lian": ['lɪɛn'],
"lian": ['lɪɛn'],
"--li": ['li'],
"li": ['li'],
"--linn": ['lĩ'],
"linn": ['lĩ'],
"--lim": ['lim'],
"lim": ['lim'],
"--ling": ['liŋ'],
"ling": ['liŋ'],
"--lin": ['lin'],
"lin": ['lin'],
"lip": ['lip'],
"--liu": ['liu'],
"liu": ['liu'],
"--liunn": ['liũ'],
"liunn": ['liũ'],
"lik": ['lɪk'],
"--lir": ['lɨ'],
"lir": ['lɨ'],
"--lng": ['lŋ̍'],
"lng": ['lŋ̍'],
"liok": ['lɪɔk'],
"lok": ['lɔk'],
"--loo": ['lɔ'],
"loo": ['lɔ'],
"--lonn": ['lɔ̃'],
"lonn": ['lɔ̃'],
"--liong": ['lɪɔŋ'],
"liong": ['lɪɔŋ'],
"--long": ['lɔŋ'],
"long": ['lɔŋ'],
"--luai": ['luai'],
"luai": ['luai'],
"--lua": ['lua'],
"lua": ['lua'],
"--luan": ['luan'],
"luan": ['luan'],
"--lue": ['lue'],
"lue": ['lue'],
"--lu": ['lu'],
"lu": ['lu'],
"--mai": ['mai'],
"mai": ['mai'],
"--mainn": ['maĩ'],
"mainn": ['maĩ'],
"mak": ['mak'],
"mah": ['maʔ'],
"--ma": ['ma'],
"ma": ['ma'],
"--mann": ['mã'],
"mann": ['mã'],
"--mian": ['mɪɛn'],
"mian": ['mɪɛn'],
"--mam": ['mam'],
"mam": ['mam'],
"map": ['map'],
"mat": ['mat'],
"--mau": ['mau'],
"mau": ['mau'],
"--me": ['me'],
"me": ['me'],
"--menn": ['mẽ'],
"menn": ['mẽ'],
"--mo": ['mo'],
"mo": ['mo'],
"--mi": ['mi'],
"mi": ['mi'],
"--minn": ['mĩ'],
"minn": ['mĩ'],
"--ming": ['miŋ'],
"ming": ['miŋ'],
"--miunn": ['miũ'],
"miunn": ['miũ'],
"mik": ['mɪk'],
"--mir": ['mɨ'],
"mir": ['mɨ'],
"--m": ['m̩'],
"m": ['m̩'],
"ḿ": ['m̩'],
"--mng": ['mŋ̍'],
"mng": ['mŋ̍'],
"mok": ['mɔk'],
"--moo": ['mɔ'],
"moo": ['mɔ'],
"--monn": ['mɔ̃'],
"monn": ['mɔ̃'],
"--mong": ['mɔŋ'],
"mong": ['mɔŋ'],
"--muai": ['muai'],
"muai": ['muai'],
"--mua": ['mua'],
"mua": ['mua'],
"--muan": ['muan'],
"muan": ['muan'],
"--mue": ['mue'],
"mue": ['mue'],
"--mu": ['mu'],
"mu": ['mu'],
"--nai": ['nai'],
"nai": ['nai'],
"--nainn": ['naĩ'],
"nainn": ['naĩ'],
"nak": ['nak'],
"--nam": ['nam'],
"nam": ['nam'],
"nah": ['naʔ'],
"--na": ['na'],
"na": ['na'],
"--nann": ['nã'],
"nann": ['nã'],
"--nian": ['nɪɛn'],
"nian": ['nɪɛn'],
"nap": ['nap'],
"nat": ['nat'],
"--nau": ['nau'],
"nau": ['nau'],
"--ne": ['ne'],
"ne": ['ne'],
"--nenn": ['nẽ'],
"nenn": ['nẽ'],
"--no": ['no'],
"no": ['no'],
"--ng": ['ŋ̍'],
"ng": ['ŋ̍'],
"--ning": ['niŋ'],
"ning": ['niŋ'],
"--ni": ['ni'],
"ni": ['ni'],
"--ninn": ['nĩ'],
"ninn": ['nĩ'],
"--niunn": ['niũ'],
"niunn": ['niũ'],
"nik": ['nɪk'],
"--nng": ['nŋ̍'],
"nng": ['nŋ̍'],
"--nir": ['nɨ'],
"nir": ['nɨ'],
"nok": ['nɔk'],
"--nong": ['nɔŋ'],
"nong": ['nɔŋ'],
"--noo": ['nɔ'],
"noo": ['nɔ'],
"--nonn": ['nɔ̃'],
"nonn": ['nɔ̃'],
"--nuai": ['nuai'],
"nuai": ['nuai'],
"--nuan": ['nuan'],
"nuan": ['nuan'],
"--nua": ['nua'],
"nua": ['nua'],
"--nue": ['nue'],
"nue": ['nue'],
"--nu": ['nu'],
"nu": ['nu'],
"iok": ['ɪɔk'],
"ok": ['ɔk'],
"--om": ['ɔm'],
"om": ['ɔm'],
"--iong": ['ɪɔŋ'],
"iong": ['ɪɔŋ'],
"--jiong": ['ʑɪɔŋ'],
"jiong": ['ʑɪɔŋ'],
"--ong": ['ɔŋ'],
"ong": ['ɔŋ'],
"--siong": ['ɕɪɔŋ'],
"siong": ['ɕɪɔŋ'],
"--oo": ['ɔ'],
"oo": ['ɔ'],
"--onn": ['ɔ̃'],
"onn": ['ɔ̃'],
"--pai": ['pai'],
"pai": ['pai'],
"--painn": ['paĩ'],
"painn": ['paĩ'],
"--phai": ['pʰai'],
"phai": ['pʰai'],
"--phainn": ['pʰaĩ'],
"phainn": ['pʰaĩ'],
"pak": ['pak'],
"phak": ['pʰak'],
"--pam": ['pam'],
"pam": ['pam'],
"--pham": ['pʰam'],
"pham": ['pʰam'],
"pah": ['paʔ'],
"--pa": ['pa'],
"pa": ['pa'],
"--pann": ['pã'],
"pann": ['pã'],
"phah": ['pʰaʔ'],
"--pha": ['pʰa'],
"pha": ['pʰa'],
"--phann": ['pʰã'],
"phann": ['pʰã'],
"--phiau": ['pʰɪaʊ'],
"phiau": ['pʰɪaʊ'],
"--piau": ['pɪaʊ'],
"piau": ['pɪaʊ'],
"pap": ['pap'],
"phap": ['pʰap'],
"pat": ['pat'],
"phat": ['pʰat'],
"--pau": ['pau'],
"pau": ['pau'],
"--phau": ['pʰau'],
"phau": ['pʰau'],
"--phian": ['pʰɪɛn'],
"phian": ['pʰɪɛn'],
"--pian": ['pɪɛn'],
"pian": ['pɪɛn'],
"--pe": ['pe'],
"pe": ['pe'],
"--penn": ['pẽ'],
"penn": ['pẽ'],
"--phe": ['pʰe'],
"phe": ['pʰe'],
"--phenn": ['pʰẽ'],
"phenn": ['pʰẽ'],
"--phio": ['pʰɪə'],
"phio": ['pʰɪə'],
"--pho": ['pʰo'],
"pho": ['pʰo'],
"--pio": ['pɪə'],
"pio": ['piu'],
"--po": ['po'],
"po": ['po'],
"--phim": ['pʰim'],
"phim": ['pʰim'],
"--pim": ['pim'],
"pim": ['pim'],
"--ping": ['piŋ'],
"ping": ['piŋ'],
"--phing": ['pʰiŋ'],
"phing": ['pʰiŋ'],
"--phin": ['pʰin'],
"phin": ['pʰin'],
"--pin": ['pin'],
"pin": ['pin'],
"--phi": ['pʰi'],
"phi": ['pʰi'],
"--phinn": ['pʰĩ'],
"phinn": ['pʰĩ'],
"--pi": ['pi'],
"pi": ['pi'],
"--pinn": ['pĩ'],
"pinn": ['pĩ'],
"phit": ['pʰit'],
"pit": ['pit'],
"--phiunn": ['pʰiũ'],
"phiunn": ['pʰiũ'],
"--piu": ['piu'],
"piu": ['piu'],
"--piunn": ['piũ'],
"piunn": ['piũ'],
"pik": ['pɪk'],
"phik": ['pʰɪk'],
"--phng": ['pʰŋ̍'],
"phng": ['pʰŋ̍'],
"--png": ['pŋ̍'],
"png": ['pŋ̍'],
"phok": ['pʰɔk'],
"pok": ['pɔk'],
"--phong": ['pʰɔŋ'],
"phong": ['pʰɔŋ'],
"--pong": ['pɔŋ'],
"pong": ['pɔŋ'],
"--phoo": ['pʰɔ'],
"phoo": ['pʰɔ'],
"--phonn": ['pʰɔ̃'],
"phonn": ['pʰɔ̃'],
"--poo": ['pɔ'],
"poo": ['pɔ'],
"--ponn": ['pɔ̃'],
"ponn": ['pɔ̃'],
"--phir": ['pʰɨ'],
"phir": ['pʰɨ'],
"--pir": ['pɨ'],
"pir": ['pɨ'],
"--phuai": ['pʰuai'],
"phuai": ['pʰuai'],
"--puai": ['puai'],
"puai": ['puai'],
"--phuan": ['pʰuan'],
"phuan": ['pʰuan'],
"--puan": ['puan'],
"puan": ['puan'],
"--phua": ['pʰua'],
"phua": ['pʰua'],
"--pua": ['pua'],
"pua": ['pua'],
"--phue": ['pʰue'],
"phue": ['pʰue'],
"--pue": ['pue'],
"pue": ['pue'],
"--phu": ['pʰu'],
"phu": ['pʰu'],
"--pu": ['pu'],
"pu": ['pu'],
"--sai": ['sai'],
"sai": ['sai'],
"--sainn": ['saĩ'],
"sainn": ['saĩ'],
"sak": ['sak'],
"--sam": ['sam'],
"sam": ['sam'],
"sap": ['sap'],
"sah": ['saʔ'],
"--sa": ['sa'],
"sa": ['sa'],
"--sann": ['sã'],
"sann": ['sã'],
"sat": ['sat'],
"--sau": ['sau'],
"sau": ['sau'],
"--se": ['se'],
"se": ['se'],
"--senn": ['sẽ'],
"senn": ['sẽ'],
"sioh": ['sɪəʔ'],
"--so": ['so'],
"so": ['so'],
"sip": ['sip'],
"sit": ['sit'],
"--siunn": ['siũ'],
"siunn": ['siũ'],
"--sng": ['sŋ̍'],
"sng": ['sŋ̍'],
"siok": ['sɪɔk'],
"sok": ['sɔk'],
"--som": ['sɔm'],
"som": ['sɔm'],
"--song": ['sɔŋ'],
"song": ['sɔŋ'],
"--soo": ['sɔ'],
"soo": ['sɔ'],
"--sonn": ['sɔ̃'],
"sonn": ['sɔ̃'],
"--suai": ['ɕuai'],
"suai": ['ɕuai'],
"--suan": ['suan'],
"suan": ['suan'],
"--sua": ['sua'],
"sua": ['sua'],
"--sue": ['sue'],
"sue": ['sue'],
"--su": ['su'],
"su": ['su'],
"--tshiau": ['tɕʰɪaʊ'],
"tshiau": ['tɕʰɪaʊ'],
"--tsiau": ['tsɪaʊ'],
"tsiau": ['tsɪaʊ'],
"--tsai": ['tsai'],
"tsai": ['tsai'],
"--tsiainn": ['tɕaĩ'],
"tsiainn": ['tɕaĩ'],
"--tai": ['tai'],
"tai": ['tai'],
"--tainn": ['taĩ'],
"tainn": ['taĩ'],
"--thai": ['tʰai'],
"thai": ['tʰai'],
"--thainn": ['tʰaĩ'],
"thainn": ['tʰaĩ'],
"tak": ['tak'],
"thak": ['tʰak'],
"--tam": ['tam'],
"tam": ['tam'],
"--tham": ['tʰam'],
"tham": ['tʰam'],
"tap": ['tap'],
"thap": ['tʰap'],
"tah": ['taʔ'],
"--ta": ['ta'],
"ta": ['ta'],
"--tann": ['tã'],
"tann": ['tã'],
"thah": ['tʰaʔ'],
"--tha": ['tʰa'],
"tha": ['tʰa'],
"--thann": ['tʰã'],
"thann": ['tʰã'],
"--thiau": ['tʰɪaʊ'],
"thiau": ['tʰɪaʊ'],
"--tiau": ['tɪaʊ'],
"tiau": ['tɪaʊ'],
"tat": ['tat'],
"that": ['tʰat'],
"--tau": ['tau'],
"tau": ['tau'],
"--thau": ['tʰau'],
"thau": ['tʰau'],
"--tsir": ['tsɨ'],
"tsir": ['tsɨ'],
"--tshio": ['tɕʰio'],
"tshio": ['tɕʰiu'],
"tshioh": ['tɕʰɪəʔ'],
"tsioh": ['tɕɪəʔ'],
"--tshian": ['tsʰɪɛn'],
"tshian": ['tsʰɪɛn'],
"--tsian": ['tsɪɛn'],
"tsian": ['tsɪɛn'],
"--thian": ['tʰɪɛn'],
"thian": ['tʰɪɛn'],
"--tian": ['tɪɛn'],
"tian": ['tɪɛn'],
"--te": ['te'],
"te": ['te'],
"--tenn": ['tẽ'],
"tenn": ['tẽ'],
"--the": ['tʰe'],
"the": ['tʰe'],
"--thenn": ['tʰẽ'],
"thenn": ['tʰẽ'],
"--thio": ['tʰɪə'],
"thio": ['tʰiu'],
"--tho": ['tʰo'],
"tho": ['tʰo'],
"tioh": ['tɪəʔ'],
"--tio": ['tɪə'],
"tio": ['tiu'],
"--to": ['to'],
"to": ['to'],
"--tshia": ['tɕʰia'],
"tshia": ['tɕʰia'],
"--tshiann": ['tɕʰiã'],
"tshiann": ['tɕʰiã'],
"tshiah": ['tɕʰiaʔ'],
"tsiah": ['tɕiaʔ'],
"--tsia": ['tɕia'],
"tsia": ['tɕia'],
"--tsiann": ['tɕiã'],
"tsiann": ['tɕiã'],
"--tshiai": ['tɕʰiai'],
"tshiai": ['tɕʰiai'],
"--tshiainn": ['tɕʰiaĩ'],
"tshiainn": ['tɕʰiaĩ'],
"tshiak": ['tɕʰiak'],
"tsiak": ['tɕiak'],
"--tshiam": ['tɕʰiam'],
"tshiam": ['tɕʰiam'],
"--tsiam": ['tɕiam'],
"tsiam": ['tɕiam'],
"tshiap": ['tɕʰiap'],
"tsiap": ['tɕiap'],
"tshiat": ['tɕʰiat'],
"tsiat": ['tɕiat'],
"--tshi": ['tsʰi'],
"tshi": ['tsʰi'],
"--tshir": ['tsʰɨ'],
"tshir": ['tsʰɨ'],
"--tsi": ['tsi'],
"tsi": ['tsi'],
"--tsinn": ['tsĩ'],
"tsinn": ['tsĩ'],
"--tshie": ['tɕʰie'],
"tshie": ['tɕʰie'],
"--tshienn": ['tɕʰiẽ'],
"tshienn": ['tɕʰiẽ'],
"--tsie": ['tɕie'],
"tsie": ['tɕie'],
"--tsienn": ['tɕiẽ'],
"tsienn": ['tɕiẽ'],
"--tsio": ['tsɪə'],
"tsio": ['tsiu'],
"--tshinn": ['tsʰĩ'],
"tshinn": ['tsʰĩ'],
"--tshiiunn": ['tɕʰiiũ'],
"tshiiunn": ['tɕʰiiũ'],
"--tshim": ['tsʰim'],
"tshim": ['tsʰim'],
"--tsim": ['tsim'],
"tsim": ['tsim'],
"--thim": ['tʰim'],
"thim": ['tʰim'],
"--tim": ['tim'],
"tim": ['tim'],
"--tshin": ['tɕʰin'],
"tshin": ['tɕʰin'],
"--tshing": ['tsʰiŋ'],
"tshing": ['tsʰiŋ'],
"--tsing": ['tsiŋ'],
"tsing": ['tsiŋ'],
"--ting": ['tiŋ'],
"ting": ['tiŋ'],
"--thing": ['tʰiŋ'],
"thing": ['tʰiŋ'],
"--thin": ['tʰin'],
"thin": ['tʰin'],
"--tin": ['tin'],
"tin": ['tin'],
"--tshioo": ['tɕʰiɔ'],
"tshioo": ['tɕʰiɔ'],
"--tshionn": ['tɕʰiɔ̃'],
"tshionn": ['tɕʰiɔ̃'],
"--tsioo": ['tɕiɔ'],
"tsioo": ['tɕiɔ'],
"--tsionn": ['tɕiɔ̃'],
"tsionn": ['tɕiɔ̃'],
"tshiok": ['tɕʰiɔk'],
"tsiok": ['tɕiɔk'],
"tship": ['tɕʰip'],
"tsip": ['tɕip'],
"tshit": ['tɕʰit'],
"tsit": ['tɕit'],
"--thi": ['tʰi'],
"thi": ['tʰi'],
"--thinn": ['tʰĩ'],
"thinn": ['tʰĩ'],
"--ti": ['ti'],
"ti": ['ti'],
"--tinn": ['tĩ'],
"tinn": ['tĩ'],
"tit": ['tit'],
"--tshiua": ['tɕʰiua'],
"tshiua": ['tɕʰiua'],
"--tshiuai": ['tɕʰiuai'],
"tshiuai": ['tɕʰiuai'],
"--tshiuan": ['tɕʰiuan'],
"tshiuan": ['tɕʰiuan'],
"--tshiu": ['tɕʰiu'],
"tshiu": ['tɕʰiu'],
"--tsiu": ['tsiu'],
"tsiu": ['tsiu'],
"--tsiiunn": ['tɕiũ'],
"tsiiunn": ['tɕiũ'],
"--tshiue": ['tɕʰiue'],
"tshiue": ['tɕʰiue'],
"--thiu": ['tʰiu'],
"thiu": ['tʰiu'],
"--thiunn": ['tʰiũ'],
"thiunn": ['tʰiũ'],
"--tiu": ['tiu'],
"tiu": ['tiu'],
"--tiunn": ['tiũ'],
"tiunn": ['tiũ'],
"tshik": ['tsʰɪk'],
"tsik": ['tsɪk'],
"tik": ['tɪk'],
"thik": ['tʰɪk'],
"--thng": ['tʰŋ̍'],
"thng": ['tʰŋ̍'],
"--tng": ['tŋ̍'],
"tng": ['tŋ̍'],
"thiok": ['tʰɪɔk'],
"thok": ['tʰɔk'],
"tiok": ['tɪɔk'],
"tok": ['tɔk'],
"--tom": ['tɔm'],
"tom": ['tɔm'],
"--tshiong": ['tɕʰɪɔŋ'],
"tshiong": ['tɕʰɪɔŋ'],
"--tsiong": ['tɕɪɔŋ'],
"tsiong": ['tɕɪɔŋ'],
"--thiong": ['tʰɪɔŋ'],
"thiong": ['tʰɪɔŋ'],
"--thong": ['tʰɔŋ'],
"thong": ['tʰɔŋ'],
"--tiong": ['tɪɔŋ'],
"tiong": ['tɪɔŋ'],
"--tong": ['tɔŋ'],
"tong": ['tɔŋ'],
"--thoo": ['tʰɔ'],
"thoo": ['tʰɔ'],
"--thonn": ['tʰɔ̃'],
"thonn": ['tʰɔ̃'],
"--too": ['tɔ'],
"too": ['tɔ'],
"--tonn": ['tɔ̃'],
"tonn": ['tɔ̃'],
"tsah": ['tsaʔ'],
"--tsa": ['tsa'],
"tsa": ['tsa'],
"--tsann": ['tsã'],
"tsann": ['tsã'],
"--tsha": ['tsʰa'],
"tsha": ['tsʰa'],
"--tshann": ['tsʰã'],
"tshann": ['tsʰã'],
"tshah": ['tsʰaʔ'],
"--tsainn": ['tsaĩ'],
"tsainn": ['tsaĩ'],
"--tshai": ['tsʰai'],
"tshai": ['tsʰai'],
"--tshainn": ['tsʰaĩ'],
"tshainn": ['tsʰaĩ'],
"tsak": ['tsak'],
"tshak": ['tsʰak'],
"--tsam": ['tsam'],
"tsam": ['tsam'],
"--tsham": ['tsʰam'],
"tsham": ['tsʰam'],
"tsap": ['tsap'],
"tshap": ['tsʰap'],
"tsat": ['tsat'],
"tshat": ['tsʰat'],
"--tsau": ['tsau'],
"tsau": ['tsau'],
"--tshau": ['tsʰau'],
"tshau": ['tsʰau'],
"--tse": ['tse'],
"tse": ['tse'],
"--tsenn": ['tsẽ'],
"tsenn": ['tsẽ'],
"--tshe": ['tsʰe'],
"tshe": ['tsʰe'],
"--tshenn": ['tsʰẽ'],
"tshenn": ['tsʰẽ'],
"--tsho": ['tsʰo'],
"tsho": ['tsʰo'],
"--tso": ['tso'],
"tso": ['tso'],
"--tsin": ['tsin'],
"tsin": ['tsin'],
"--tshiunn": ['tsʰiũ'],
"tshiunn": ['tsʰiũ'],
"--tsiunn": ['tsiũ'],
"tsiunn": ['tsiũ'],
"--tshng": ['tsʰŋ̍'],
"tshng": ['tsʰŋ̍'],
"--tsng": ['tsŋ̍'],
"tsng": ['tsŋ̍'],
"--tshoo": ['tsʰɔ'],
"tshoo": ['tsʰɔ'],
"--tshonn": ['tsʰɔ̃'],
"tshonn": ['tsʰɔ̃'],
"--tsoo": ['tsɔ'],
"tsoo": ['tsɔ'],
"--tsonn": ['tsɔ̃'],
"tsonn": ['tsɔ̃'],
"tshok": ['tsʰɔk'],
"tsok": ['tsɔk'],
"--tshong": ['tsʰɔŋ'],
"tshong": ['tsʰɔŋ'],
"--tsong": ['tsɔŋ'],
"tsong": ['tsɔŋ'],
"--tshua": ['tsʰua'],
"tshua": ['tsʰua'],
"--tsua": ['tɕua'],
"tsua": ['tɕua'],
"--tshuai": ['tsʰuai'],
"tshuai": ['tsʰuai'],
"--tsuai": ['tɕuai'],
"tsuai": ['tɕuai'],
"--tshuan": ['tsʰuan'],
"tshuan": ['tsʰuan'],
"--tsuan": ['tɕuan'],
"tsuan": ['tɕuan'],
"--tshu": ['tsʰu'],
"tshu": ['tsʰu'],
"--tsu": ['tsu'],
"tsu": ['tsu'],
"--tshue": ['tsʰue'],
"tshue": ['tsʰue'],
"--tsue": ['tɕue'],
"tsue": ['tɕue'],
"--thir": ['tʰɨ'],
"thir": ['tʰɨ'],
"--tir": ['tɨ'],
"tir": ['tɨ'],
"--thuai": ['tʰuai'],
"thuai": ['tʰuai'],
"--tuai": ['tuai'],
"tuai": ['tuai'],
"--thuan": ['tʰuan'],
"thuan": ['tʰuan'],
"--tuan": ['tuan'],
"tuan": ['tuan'],
"--thua": ['tʰua'],
"thua": ['tʰua'],
"--tua": ['tua'],
"tua": ['tua'],
"--thue": ['tʰue'],
"thue": ['tʰue'],
"--tue": ['tue'],
"tue": ['tue'],
"--thu": ['tʰu'],
"thu": ['tʰu'],
"--tu": ['tu'],
"tu": ['tu'],
"--uai": ['uai'],
"uai": ['uai'],
"--uan": ['uan'],
"uan": ['uan'],
"--ua": ['ua'],
"ua": ['ua'],
"--ue": ['ue'],
"ue": ['ue'],
"--u": ['u'],
"u": ['u'],
    #自動的に追加したもの
    #以前作ったもの
    # "honn": ["ɔ̃"],
    # "uainn": ["uãi"],
    # "uann": ["uã"],
    # "ueh": ["ueʔ"],
    # "uh": ["uʔ"],
    # "ngh": ["ŋʔ"],
    # "ok": ["ɔk"],
    # "om": ["ɔm"],
    # "ong": ["ɔŋ"],
    # "onn": ["ɔ̃"],
    # "ooh": ["ɔʔ"],
    # "op": ["ɔp"],
    # "iuh": ["iuʔ"],
    # "iunn": ["iũ"],
    # "ng": ["ŋ"],
    # "ioh": ["ioʔ"],
    # "iok": ["iɔk"],
    # "iong": ["iɔŋ"],
    # "ing": ["ieŋ"],
    # "inn": ["ĩ"],
    # "innh": ["ĩʔ"],
    # "iauh": ["iauʔ"],
    # "iaunnh": ["iãu"],
    # "ih": ["iʔ"],
    # "ik": ["iek"],
    # "inn": ["◌̃"],
    # "o": ["o"],
    # "oo": ["ɔ"],
    # "pi": ["pi"],
    # "phi": ["pʰ"],
    # "si": ["si"],
    # "ti": ["ti"],
    # "thi": ["tʰ"],
    # "tsi": ["t͡s"],
    # "tshi": ["t͡sʰ"],
    # "u": ["u"],
    # "ah": ["aʔ"],
    # "ainn": ["ãi"],
    # "annh": ["ãʔ"],
    # "auh": ["auʔ"],
    # "eh": ["eʔ"],
    # "enn": ["ẽ"],
    # "ennh": ["ẽʔ"],
    # "iah": ["iaʔ"],
    # "ah": ["aʔ"],
    # "ah": ["aʔ"],
    # "aŋ": ["aŋ"],
    # "au": ["au"],
    # "e": ["e"],
    # "ia": ["ia"],
    # "iak": ["iak"],
    # "iam": ["iam"],
    # "ian": ["ian"],
    # "iaŋ": ["iaŋ"],
    # "iann": ["iã"],
    # "iannh": ["iãʔ"],
    # "a": ["a"],
    # "bi": ["bi"],
    # "e": ["e"],
    # "gi": ["gi"],
    # "h": ["h"],
    # "i": ["i"],
    # "dz": ["ji"],
    # "ki": ["ki"],
    # "kʰ": ["khi"],
    # "li": ["li"],
    # "mi": ["mi"],
    # "ni": ["ni"],
    # "ŋ": ["ngi"],
    # "inn": ["◌̃"],
    # "o": ["o"],
    # "oo": ["ɔ"],
    # "pi": ["pi"],
    # "phi": ["phi"],
    # "si": ["si"],
    # "ti": ["ti"],
    # "thi": ["thi"],
    # "tsi": ["tsi"],
    # "tshi": ["tshi"],
    # "u": ["u"],
    # "ah": ["aʔ"],
    # "ainn": ["ãi"],
    # "aŋ": ["aŋ"],
    # "annh": ["ãʔ"],
    # "au": ["au"],
    # "auh": ["auʔ"],
    # "e": ["e"],
    # "eh": ["eʔ"],
    # "enn": ["ẽ"],
    # "ennh": ["ẽʔ"],
    # "ia": ["ia"],
    # "iah": ["iaʔ"],
    # "iak": ["iak"],
    # "iam": ["iam"],
    # "ian": ["ian"],
    # "iaŋ": ["iaŋ"],
    # "iann": ["iã"],
    # "iannh": ["iãʔ"],
    # "-h": ["-ʔ"],
    # "-k": ["-k"],
    # "-m": ["-m"],
    # "-n": ["n"],
    # "-ng": ["əŋ"],
    # "-p": ["-p"],
    # "-t": ["-t"],
    # "a": ["a"],
    # "ah": ["aʔ"],
    # "ai": ["ai"],
    # "ainn": ["ãi"],
    # "ak": ["ak"],
    # "am": ["am"],
    # "an": ["an"],
    # "ang": ["aŋ"],
    # "ann": ["ã"],
    # "annh": ["ãʔ"],
    # "ap": ["ap"],
    # "at": ["at"],
    # "au": ["au"],
    # "auh": ["auʔ"],
    # "aunn": ["ãũ"],
    # "b": ["b"],
    # "e": ["e"],
    # "ee": ["ɛ"],
    # "eh": ["eʔ"],
    # "enn": ["ẽ"],
    # "ennh": ["ẽʔ"],
    # "er": ["ə"],
    # "g": ["g"],
    # "h": ["h"],
    # "i": ["i"],
    # "ia": ["ia"],
    # "iah": ["iaʔ"],
    # "iak": ["iak"],
    # "iam": ["iam"],
    # "ian": ["ian"],
    # "iang": ["iaŋ"],
    # "iann": ["iã"],
    # "iannh": ["iãʔ"],
    # "iap": ["iap"],
    # "iat": ["iat"],
    # "iau": ["iau"],
    # "iauh": ["iauʔ"],
    # "iaunn": ["iãu"],
    # "ih": ["iʔ"],
    # "ik": ["ik"],
    # "im": ["im"],
    # "in": ["in"],
    # "ing": ["iŋ"],
    # "inn": ["ĩ"],
    # "innh": ["ĩʔ"],
    # "io": ["iə"],
    # "ioh": ["iəʔ"],
    # "iok": ["iɔk"],
    # "iong": ["iɔŋ"],
    # "ip": ["ip"],
    # "ir": ["ɨ"],
    # "it": ["it"],
    # "iu": ["iu"],
    # "iuh": ["iuʔ"],
    # "iunn": ["iũ"],
    # "j": ["dz"],
    # "ji": ["d͡ʑ"],
    # "k": ["k"],
    # "kh": ["kʰ"],
    # "l": ["l"],
    # "m": ["m̩"],
    # "mh": ["mʔ"],
    # "n": ["n"],
    # "ng": ["ŋ̍"],
    # "ngh": ["ŋʔ"],
    # "o": ["o"],
    # "oh": ["əʔ"],
    # "ok": ["ɔk"],
    # "om": ["ɔm"],
    # "ong": ["ɔŋ"],
    # "onn": ["ɔ̃"],
    # "oo": ["ɔ"],
    # "ooh": ["ɔʔ"],
    # "op": ["ɔp"],
    # "or": ["ə"],
    # "p": ["p"],
    # "ph": ["pʰ"],
    # "s": ["s"],
    # "si": ["ɕ"],
    # "t": ["t"],
    # "th": ["tʰ"],
    # "ts": ["t͡s"],
    # "tsh": ["t͡sʰ"],
    # "tshi": ["t͡ɕʰ"],
    # "tsi": ["t͡ɕ"],
    # "u": ["u"],
    # "ua": ["ua"],
    # "uah": ["uaʔ"],
    # "uai": ["uai"],
    # "uainn": ["uãi"],
    # "uan": ["uan"],
    # "uann": ["uã"],
    # "uat": ["uat"],
    # "ue": ["ue"],
    # "ueh": ["ueʔ"],
    # "uh": ["uʔ"],
    # "ui": ["ui"],
    # "un": ["un"],
    # "unn": ["ũ"],
    # "ut": ["ut"],

    #tuika
    "uainn": ["uãi"],
    "uann": ["uã"],
    "ueh": ["ueʔ"],
    "uh": ["uʔ"],
    "ngh": ["ŋʔ"],
    "ok": ["ɔk"],
    "om": ["ɔm"],
    "ong": ["ɔŋ"],
    "onn": ["ɔ̃"],
    "ooh": ["ɔʔ"],
    "op": ["ɔp"],
    "iuh": ["iuʔ"],
    "iunn": ["iũ"],
    "ng": ["ŋ"],
    "ioh": ["ioʔ"],
    "iok": ["iɔk"],
    "iong": ["iɔŋ"],
    "ing": ["ieŋ"],
    "inn": ["ĩ"],
    "innh": ["ĩʔ"],
    "iauh": ["iauʔ"],
    "iaunnh": ["iãu"],
    "ih": ["iʔ"],
    "ik": ["iek"],
    "inn": ["◌̃"],
    "o": ["o"],
    "oo": ["ɔ"],
    "pi": ["pi"],
    "phi": ["pʰ"],
    "si": ["si"],
    "ti": ["ti"],
    "thi": ["tʰ"],
    "tsi": ["t͡s"],
    "tshi": ["t͡sʰ"],
    "u": ["u"],
    "ah": ["aʔ"],
    "ainn": ["ãi"],
    "annh": ["ãʔ"],
    "auh": ["auʔ"],
    "eh": ["eʔ"],
    "enn": ["ẽ"],
    "ennh": ["ẽʔ"],
    "iah": ["iaʔ"],
    "ah": ["aʔ"],
    "ah": ["aʔ"],
    "aŋ": ["aŋ"],
    "au": ["au"],
    "e": ["e"],
    "ia": ["ia"],
    "iak": ["iak"],
    "iam": ["iam"],
    "ian": ["ian"],
    "iaŋ": ["iaŋ"],
    "iann": ["iã"],
    "iannh": ["iãʔ"],
    "a": ["a"],
    "bi": ["bi"],
    "e": ["e"],
    "gi": ["gi"],
    "h": ["h"],
    "i": ["i"],
    "dz": ["ji"],
    "ki": ["ki"],
    "kʰ": ["khi"],
    "li": ["li"],
    "mi": ["mi"],
    "ni": ["ni"],
    "ŋ": ["ngi"],
    "inn": ["◌̃"],
    "o": ["o"],
    "oo": ["ɔ"],
    "pi": ["pi"],
    "phi": ["phi"],
    "si": ["si"],
    "ti": ["ti"],
    "thi": ["thi"],
    "tsi": ["tsi"],
    "tshi": ["tshi"],
    "u": ["u"],
    "ah": ["aʔ"],
    "ainn": ["ãi"],
    "aŋ": ["aŋ"],
    "annh": ["ãʔ"],
    "au": ["au"],
    "auh": ["auʔ"],
    "e": ["e"],
    "eh": ["eʔ"],
    "enn": ["ẽ"],
    "ennh": ["ẽʔ"],
    "ia": ["ia"],
    "iah": ["iaʔ"],
    "iak": ["iak"],
    "iam": ["iam"],
    "ian": ["ian"],
    "iaŋ": ["iaŋ"],
    "iann": ["iã"],
    "iannh": ["iãʔ"],
    "-h": ["-ʔ"],
    "-k": ["-k"],
    "-m": ["-m"],
    "-n": ["n"],
    "-ng": ["əŋ"],
    "-p": ["-p"],
    "-t": ["-t"],
    "a": ["a"],
    "ah": ["aʔ"],
    "ai": ["ai"],
    "ainn": ["ãi"],
    "ak": ["ak"],
    "am": ["am"],
    "an": ["an"],
    "ang": ["aŋ"],
    "ann": ["ã"],
    "annh": ["ãʔ"],
    "ap": ["ap"],
    "at": ["at"],
    "au": ["au"],
    "auh": ["auʔ"],
    "aunn": ["ãũ"],
    "b": ["b"],
    "e": ["e"],
    "ee": ["ɛ"],
    "eh": ["eʔ"],
    "enn": ["ẽ"],
    "ennh": ["ẽʔ"],
    "er": ["ə"],
    "g": ["g"],
    "h": ["h"],
    "i": ["i"],
    "ia": ["ia"],
    "iah": ["iaʔ"],
    "iak": ["iak"],
    "iam": ["iam"],
    "ian": ["ian"],
    "iang": ["iaŋ"],
    "iann": ["iã"],
    "iannh": ["iãʔ"],
    "iap": ["iap"],
    "iat": ["iat"],
    "iau": ["iau"],
    "iauh": ["iauʔ"],
    "iaunn": ["iãu"],
    "ih": ["iʔ"],
    "ik": ["ik"],
    "im": ["im"],
    "in": ["in"],
    "ing": ["iŋ"],
    "inn": ["ĩ"],
    "innh": ["ĩʔ"],
    "io": ["iə"],
    "ioh": ["iəʔ"],
    "iok": ["iɔk"],
    "iong": ["iɔŋ"],
    "ip": ["ip"],
    "ir": ["ɨ"],
    "it": ["it"],
    "iu": ["iu"],
    "iuh": ["iuʔ"],
    "iunn": ["iũ"],
    "j": ["dz"],
    "ji": ["d͡ʑ"],
    "k": ["k"],
    "kh": ["kʰ"],
    "l": ["l"],
    "m": ["m̩"],
    "mh": ["mʔ"],
    "n": ["n"],
    "ng": ["ŋ̍"],
    "ngh": ["ŋʔ"],
    "o": ["o"],
    "oh": ["əʔ"],
    "ok": ["ɔk"],
    "om": ["ɔm"],
    "ong": ["ɔŋ"],
    "onn": ["ɔ̃"],
    "oo": ["ɔ"],
    "ooh": ["ɔʔ"],
    "op": ["ɔp"],
    "or": ["ə"],
    "p": ["p"],
    "ph": ["pʰ"],
    "s": ["s"],
    "si": ["ɕ"],
    "t": ["t"],
    "th": ["tʰ"],
    "ts": ["t͡s"],
    "tsh": ["t͡sʰ"],
    "tshi": ["t͡ɕʰ"],
    "tsi": ["t͡ɕ"],
    "u": ["u"],
    "ua": ["ua"],
    "uah": ["uaʔ"],
    "uai": ["uai"],
    "uainn": ["uãi"],
    "uan": ["uan"],
    "uann": ["uã"],
    "uat": ["uat"],
    "ue": ["ue"],
    "ueh": ["ueʔ"],
    "uh": ["uʔ"],
    "ui": ["ui"],
    "un": ["un"],
    "unn": ["ũ"],
    "ut": ["ut"],
    
    
    #ないものを独自に追加 あくまでも参考
  "aih": ["aɪʔ"],
  "ban": ["ban"],
  "bang": ["baŋ"],
  "beh": ["beʔ"],
  "bih": ["biʔ"],
  "buah": ["buaʔ"],
  "bueh": ["bueʔ"],
  "bui": ["bui"],
  "bun": ["bun"],
  "but": ["but"],
  "gan": ["ɡan"],
  "gang": ["ɡaŋ"],
  "gia": ["ɡia"],
  "giah": ["ɡiaʔ"],
  "giam": ["ɡiam"],
  "giang": ["ɡiaŋ"],
  "giap": ["ɡiap"],
  "giat": ["ɡiat"],
  "gui": ["ɡui"],
  "haih": ["haɪʔ"],
  "han": ["han"],
  "hang": ["haŋ"],
  "hannh": ["haŋʔ"],
  "heh": ["heʔ"],
  "hia": ["hia"],
  "hiah": ["hiaʔ"],
  "hiam": ["hiam"],
  "hiang": ["hiaŋ"],
  "hiann": ["hiaŋ"],
  "hiannh": ["hiaŋʔ"],
  "hiat": ["hiat"],
  "hiauh": ["hiɑʊʔ"],
  "hmh": ["hmʔ"],
  "hm̍h": ["hm̍ʔ"],
  "hngh": ["hŋʔ"],
  "hn̄g": ["hn̄ɡ"],
  "honnh": ["hoŋʔ"],
  "hooh": ["hoːʔ"],
  "huah": ["huaʔ"],
  "huainn": ["huaiŋ"],
  "huann": ["huaŋ"],
  "huat": ["huat"],
  "hueh": ["hueʔ"],
  "hui": ["hui"],
  "hun": ["hun"],
  "hut": ["hut"],
  "jun": ["ʒun"],
  "kan": ["kan"],
  "kang": ["kaŋ"],
  "kauh": ["kaʊʔ"],
  "keh": ["keʔ"],
  "khan": ["kʰan"],
  "khang": ["kʰaŋ"],
  "kheh": ["kʰeʔ"],
  "khia": ["kʰia"],
  "khiam": ["kʰiam"],
  "khiang": ["kʰiaŋ"],
  "khiap": ["kʰiap"],
  "khiat": ["kʰiat"],
  "khih": ["kʰiʔ"],
  "khuah": ["kʰuaʔ"],
  "khuann": ["kʰuaŋ"],
  "khuat": ["kʰuat"],
  "khuh": ["kʰuʔ"],
  "khui": ["kʰui"],
  "khuinn": ["kʰuaiŋ"],
  "khun": ["kʰun"],
  "khut": ["kʰut"],
  "khǹg": ["kʰŋ"],
  "kia": ["kia"],
  "kiam": ["kiam"],
  "kiann": ["kiaŋ"],
  "kiap": ["kiap"],
  "kiat": ["kiat"],
  "koh": ["koʔ"],
  "kuah": ["kuaʔ"],
  "kuainn": ["kuaiŋ"],
  "kuann": ["kuaŋ"],
  "kuat": ["kuat"],
  "kueh": ["kueʔ"],
  "kui": ["kui"],
  "kun": ["kun"],
  "kut": ["kut"],
  "kǹg": ["kŋ"],
  "lan": ["lan"],
  "lang": ["laŋ"],
  "leh": ["leʔ"],
  "liah": ["liaʔ"],
  "liam": ["liam"],
  "liang": ["liaŋ"],
  "liap": ["liap"],
  "lih": ["liʔ"],
  "loh": ["loʔ"],
  "looh": ["loːʔ"],
  "lop": ["lop"],
  "luah": ["luaʔ"],
  "luh": ["luʔ"],
  "lui": ["lui"],
  "lun": ["lun"],
  "lut": ["lut"],
  "mauh": ["maʊʔ"],
  "meh": ["meʔ"],
  "mia": ["mia"],
  "miau": ["miau"],
  "mih": ["miʔ"],
  "mooh": ["moːʔ"],
  "mui": ["mui"],
  "nauh": ["naʊʔ"],
  "neh": ["neʔ"],
  "nga": ["ŋa"],
  "ngai": ["ŋaɪ"],
  "ngau": ["ŋaʊ"],
  "nge": ["ŋe"],
  "ngeh": ["ŋeʔ"],
  "ngia": ["ŋia"],
  "ngiau": ["ŋiau"],
  "nia": ["nia"],
  "niau": ["niau"],
  "nih": ["niʔ"],
  "niu": ["niu"],
  "nn̄g": ["n̄ŋ"],
  "nǹg": ["nŋ"],
  "n̄g": ["ŋ̄"],
  "pa2–bue": ["pa-bue"],
  "pan": ["pan"],
  "pang": ["paŋ"],
  "peh": ["peʔ"],
  "phan": ["pʰan"],
  "phang": ["pʰaŋ"],
  "phiah": ["pʰiaʔ"],
  "phiang": ["pʰiaŋ"],
  "phiann": ["pʰiaŋ"],
  "phiat": ["pʰiat"],
  "phih": ["pʰiʔ"],
  "phoh": ["pʰoʔ"],
  "phuah": ["pʰuaʔ"],
  "phuann": ["pʰuaŋ"],
  "phuat": ["pʰuat"],
  "phui": ["pʰui"],
  "phun": ["pʰun"],
  "phut": ["pʰut"],
  "piah": ["piaʔ"],
  "piak": ["piak"],
  "piang": ["piaŋ"],
  "piann": ["piaŋ"],
  "piat": ["piat"],
  "pih": ["piʔ"],
  "pn̄g": ["pŋ̄"],
  "poh": ["poʔ"],
  "puah": ["puaʔ"],
  "puann": ["puaŋ"],
  "puat": ["puat"],
  "pueh": ["pueʔ"],
  "puh": ["puʔ"],
  "pui": ["pui"],
  "pun": ["pun"],
  "put": ["put"],
  "san": ["san"],
  "sang": ["saŋ"],
  "sannh": ["saŋʔ"],
  "seh": ["seʔ"],
  "siang": ["siaŋ"],
  "sih": ["siʔ"],
  "soh": ["soʔ"],
  "suah": ["suaʔ"],
  "suainn": ["suaiŋ"],
  "suann": ["suaŋ"],
  "suat": ["suat"],
  "sueh": ["sueʔ"],
  "suh": ["suʔ"],
  "sui": ["sui"],
  "sun": ["sun"],
  "sut": ["sut"],
  "sǹg": ["sŋ"],
  "tan": ["tan"],
  "tang": ["taŋ"],
  "tauh": ["taʊʔ"],
  "teh": ["teʔ"],
  "than": ["tʰan"],
  "thang": ["tʰaŋ"],
  "theh": ["tʰeʔ"],
  "thiah": ["tʰiaʔ"],
  "thiam": ["tʰiam"],
  "thiann": ["tʰiaŋ"],
  "thiap": ["tʰiap"],
  "thih": ["tʰiʔ"],
  "thn̄g": ["tʰŋ̄"],
  "thoh": ["tʰoʔ"],
  "thuah": ["tʰuaʔ"],
  "thuann": ["tʰuaŋ"],
  "thuat": ["tʰuat"],
  "thuh": ["tʰuʔ"],
  "thui": ["tʰui"],
  "thun": ["tʰun"],
  "thut": ["tʰut"],
  "thǹg": ["tʰŋ"],
  "tiah": ["tiaʔ"],
  "tiam": ["tiam"],
  "tiann": ["tiaŋ"],
  "tiap": ["tiap"],
  "tiat": ["tiat"],
  "tih": ["tiʔ"],
  "tiuh": ["tiuʔ"],
  "tn̄g": ["tŋ̄"],
  "toh": ["toʔ"],
  "tsan": ["tsan"],
  "tsang": ["tsaŋ"],
  "tseh": ["tseʔ"],
  "tshan": ["tʂan"],
  "tshang": ["tʂaŋ"],
  "tsheh": ["tʂeʔ"],
  "tshiang": ["tʂiaŋ"],
  "tshih": ["tʂiʔ"],
  "tshuah": ["tʂuaʔ"],
  "tshuann": ["tʂuaŋ"],
  "tshuh": ["tʂuʔ"],
  "tshui": ["tʂui"],
  "tshun": ["tʂun"],
  "tshut": ["tʂut"],
  "tshǹg": ["tʂŋ"],
  "tsiang": ["tsiaŋ"],
  "tsih": ["tsiʔ"],
  "tsiuh": ["tsiuʔ"],
  "tsn̄g": ["tsŋ̄"],
  "tsoh": ["tsoʔ"],
  "tsuah": ["tsuaʔ"],
  "tsuainn": ["tsuaiŋ"],
  "tsuann": ["tsuaŋ"],
  "tsuat": ["tsuat"],
  "tsuh": ["tsuʔ"],
  "tsui": ["tsui"],
  "tsun": ["tsun"],
  "tsut": ["tsut"],
  "tsǹg": ["tsŋ"],
  "tuann": ["tuaŋ"],
  "tuat": ["tuat"],
  "tuh": ["tuʔ"],
  "tui": ["tui"],
  "tun": ["tun"],
  "tǹg": ["tŋ"],
  "uang": ["uaŋ"],
  "ǹg": ["ŋ"],
  "i1‑ki3": ["i˧-ki˧˦"],



    
    
    
    #tuika http://mirlab.org/jang/app/asr/dict/taiwanese/mspDatabaseList.asp
}
